// Auto-generated from 0063_ai_food_images.sql
// Maps food name patterns to image paths
// 646 rules

import { foodImageUrl } from './imageUrl';

const R = [
  ["/foods/chicken_breast.jpg",[["chicken breast"], ["pechuga de pollo"]]],
  ["/foods/chicken_thigh.jpg",[["chicken thigh"], ["muslo de pollo"]]],
  ["/foods/ground_turkey.jpg",[["ground turkey"]]],
  ["/foods/ground_beef_90.jpg",[["ground beef", "90"], ["ground beef (90"]]],
  ["/foods/ground_beef_80.jpg",[["ground beef", "80"], ["ground beef (80"]]],
  ["/foods/salmon_fillet.jpg",[["salmon fillet"], ["salmon", "cooked"]]],
  ["/foods/tuna_canned.jpg",[["tuna", "canned"], ["tuna", "water"], ["at\u00e3\u00ban"]]],
  ["/foods/shrimp_cooked.jpg",[["shrimp", "cooked"]]],
  ["/foods/tilapia_cooked.jpg",[["tilapia"]]],
  ["/foods/pork_tenderloin.jpg",[["pork tenderloin"]]],
  ["/foods/steak_sirloin.jpg",[["sirloin"]]],
  ["/foods/steak_ribeye.jpg",[["ribeye"]]],
  ["/foods/turkey_breast_deli.jpg",[["turkey breast", "deli"]]],
  ["/foods/bacon_cooked.jpg",[["bacon", "cooked"], ["bacon"]]],
  ["/foods/sausage_link.jpg",[["sausage link"]]],
  ["/foods/cod_baked.jpg",[["cod", "baked"]]],
  ["/foods/halibut_baked.jpg",[["halibut"]]],
  ["/foods/sardines_canned.jpg",[["sardine"]]],
  ["/foods/catfish_baked.jpg",[["catfish"]]],
  ["/foods/mahi_mahi.jpg",[["mahi"]]],
  ["/foods/crab_meat.jpg",[["crab"]]],
  ["/foods/lobster_steamed.jpg",[["lobster"]]],
  ["/foods/beef_brisket.jpg",[["brisket"]]],
  ["/foods/lamb_chop.jpg",[["lamb chop"]]],
  ["/foods/veal_cutlet.jpg",[["veal"]]],
  ["/foods/turkey_burger.jpg",[["turkey burger"]]],
  ["/foods/bison_burger.jpg",[["bison"]]],
  ["/foods/venison_roasted.jpg",[["venison"]]],
  ["/foods/pork_chop.jpg",[["pork chop"]]],
  ["/foods/lamb_ground.jpg",[["lamb", "ground"]]],
  ["/foods/egg_whole.jpg",[["egg", "large"], ["egg (whole, large)"]]],
  ["/foods/egg_white.jpg",[["egg white"]]],
  ["/foods/greek_yogurt_0.jpg",[["greek yogurt", "0"]]],
  ["/foods/greek_yogurt_2.jpg",[["greek yogurt", "2"]]],
  ["/foods/cottage_cheese_2.jpg",[["cottage cheese", "2"]]],
  ["/foods/milk_whole.jpg",[["milk (whole)"]]],
  ["/foods/milk_2percent.jpg",[["milk (2%)"]]],
  ["/foods/milk_skim.jpg",[["milk (skim)"]]],
  ["/foods/cheese_cheddar.jpg",[["cheddar"]]],
  ["/foods/cheese_mozzarella.jpg",[["mozzarella"]]],
  ["/foods/butter.jpg",[["butter"]]],
  ["/foods/cream_cheese.jpg",[["cream cheese"]]],
  ["/foods/white_rice.jpg",[["white rice", "cooked"]]],
  ["/foods/brown_rice.jpg",[["brown rice"]]],
  ["/foods/jasmine_rice.jpg",[["jasmine rice"]]],
  ["/foods/quinoa.jpg",[["quinoa"]]],
  ["/foods/pasta_cooked.jpg",[["pasta (cooked)"]]],
  ["/foods/bread_white.jpg",[["bread", "white"], ["bread \u00e2\u20ac\u201d white"]]],
  ["/foods/bread_whole_wheat.jpg",[["bread", "whole wheat"], ["bread \u00e2\u20ac\u201d whole wheat"]]],
  ["/foods/tortilla_flour.jpg",[["tortilla", "flour"]]],
  ["/foods/tortilla_corn.jpg",[["tortilla", "corn"]]],
  ["/foods/oatmeal.jpg",[["oatmeal", "dry"]]],
  ["/foods/bagel_plain.jpg",[["bagel", "plain"]]],
  ["/foods/potato_baked.jpg",[["potato", "baked", "medium"]]],
  ["/foods/sweet_potato_baked.jpg",[["sweet potato", "baked"]]],
  ["/foods/couscous.jpg",[["couscous"]]],
  ["/foods/bulgur_wheat.jpg",[["bulgur"]]],
  ["/foods/farro.jpg",[["farro"]]],
  ["/foods/barley.jpg",[["barley"]]],
  ["/foods/wild_rice.jpg",[["wild rice"]]],
  ["/foods/banana.jpg",[["banana"]]],
  ["/foods/apple.jpg",[["apple"]]],
  ["/foods/orange.jpg",[["orange"]]],
  ["/foods/blueberries.jpg",[["blueberries"]]],
  ["/foods/strawberries.jpg",[["strawberries"]]],
  ["/foods/grapes.jpg",[["grapes"]]],
  ["/foods/avocado.jpg",[["avocado"]]],
  ["/foods/mango.jpg",[["mango"]]],
  ["/foods/watermelon.jpg",[["watermelon"]]],
  ["/foods/pineapple.jpg",[["pineapple"]]],
  ["/foods/peach.jpg",[["peach"]]],
  ["/foods/plum.jpg",[["plum"]]],
  ["/foods/kiwi.jpg",[["kiwi"]]],
  ["/foods/pomegranate_seeds.jpg",[["pomegranate"]]],
  ["/foods/figs_fresh.jpg",[["figs", "fresh"]]],
  ["/foods/dates_medjool.jpg",[["dates", "medjool"]]],
  ["/foods/dried_cranberries.jpg",[["dried cranberries"]]],
  ["/foods/raisins.jpg",[["raisins"]]],
  ["/foods/raspberries.jpg",[["raspberries"]]],
  ["/foods/blackberries.jpg",[["blackberries"]]],
  ["/foods/cantaloupe.jpg",[["cantaloupe"]]],
  ["/foods/honeydew.jpg",[["honeydew"]]],
  ["/foods/broccoli.jpg",[["broccoli", "cooked"]]],
  ["/foods/spinach_raw.jpg",[["spinach", "raw"]]],
  ["/foods/mixed_salad_greens.jpg",[["mixed salad"], ["salad greens"]]],
  ["/foods/carrots_raw.jpg",[["carrots", "raw"], ["carrots (raw)"]]],
  ["/foods/bell_pepper.jpg",[["bell pepper"]]],
  ["/foods/tomato.jpg",[["tomato"]]],
  ["/foods/cucumber.jpg",[["cucumber"]]],
  ["/foods/green_beans.jpg",[["green beans"]]],
  ["/foods/asparagus.jpg",[["asparagus"]]],
  ["/foods/corn_cooked.jpg",[["corn", "cooked"]]],
  ["/foods/mushrooms_raw.jpg",[["mushrooms", "raw"]]],
  ["/foods/onion_raw.jpg",[["onion", "raw"]]],
  ["/foods/zucchini_cooked.jpg",[["zucchini"]]],
  ["/foods/kale_raw.jpg",[["kale"]]],
  ["/foods/cauliflower_raw.jpg",[["cauliflower"]]],
  ["/foods/brussels_sprouts.jpg",[["brussels"]]],
  ["/foods/eggplant_cooked.jpg",[["eggplant"]]],
  ["/foods/artichoke_cooked.jpg",[["artichoke"]]],
  ["/foods/beets_cooked.jpg",[["beets"]]],
  ["/foods/cabbage_raw.jpg",[["cabbage"]]],
  ["/foods/celery_raw.jpg",[["celery"]]],
  ["/foods/radishes_raw.jpg",[["radish"]]],
  ["/foods/snap_peas_raw.jpg",[["snap peas"]]],
  ["/foods/black_beans.jpg",[["black beans", "cooked"]]],
  ["/foods/chickpeas.jpg",[["chickpeas"]]],
  ["/foods/lentils.jpg",[["lentils"]]],
  ["/foods/peanut_butter.jpg",[["peanut butter"]]],
  ["/foods/almond_butter.jpg",[["almond butter"]]],
  ["/foods/almonds.jpg",[["almonds"]]],
  ["/foods/walnuts.jpg",[["walnuts"]]],
  ["/foods/cashews.jpg",[["cashews"]]],
  ["/foods/mixed_nuts.jpg",[["mixed nuts"]]],
  ["/foods/pistachios.jpg",[["pistachios"]]],
  ["/foods/macadamia_nuts.jpg",[["macadamia"]]],
  ["/foods/pecans.jpg",[["pecans"]]],
  ["/foods/pine_nuts.jpg",[["pine nuts"]]],
  ["/foods/sunflower_seeds.jpg",[["sunflower seeds"]]],
  ["/foods/pumpkin_seeds.jpg",[["pumpkin seeds"]]],
  ["/foods/chia_seeds.jpg",[["chia seeds"]]],
  ["/foods/flax_seeds.jpg",[["flax"]]],
  ["/foods/hemp_hearts.jpg",[["hemp"]]],
  ["/foods/tahini.jpg",[["tahini"]]],
  ["/foods/kidney_beans.jpg",[["kidney beans"]]],
  ["/foods/pinto_beans.jpg",[["pinto beans"]]],
  ["/foods/navy_beans.jpg",[["navy beans"]]],
  ["/foods/refried_beans.jpg",[["refried beans"]]],
  ["/foods/tofu_firm.jpg",[["tofu"]]],
  ["/foods/tempeh.jpg",[["tempeh"]]],
  ["/foods/seitan.jpg",[["seitan"]]],
  ["/foods/edamame.jpg",[["edamame"]]],
  ["/foods/beyond_meat_burger.jpg",[["beyond meat"]]],
  ["/foods/impossible_burger.jpg",[["impossible burger patty"]]],
  ["/foods/whey_protein_shake.jpg",[["whey protein"]]],
  ["/foods/casein_protein_shake.jpg",[["casein protein"]]],
  ["/foods/mass_gainer_shake.jpg",[["mass gainer"]]],
  ["/foods/protein_bar.jpg",[["protein bar", "average"]]],
  ["/foods/olive_oil.jpg",[["olive oil"]]],
  ["/foods/coconut_oil.jpg",[["coconut oil"]]],
  ["/foods/honey.jpg",[["honey"]]],
  ["/foods/soy_sauce.jpg",[["soy sauce"]]],
  ["/foods/hot_sauce.jpg",[["hot sauce"]]],
  ["/foods/ketchup.jpg",[["ketchup"]]],
  ["/foods/mustard.jpg",[["mustard"]]],
  ["/foods/ranch_dressing.jpg",[["ranch dressing"]]],
  ["/foods/salsa.jpg",[["salsa"]]],
  ["/foods/hummus.jpg",[["hummus"]]],
  ["/foods/guacamole.jpg",[["guacamole"]]],
  ["/foods/bbq_sauce.jpg",[["bbq sauce"]]],
  ["/foods/mayonnaise.jpg",[["mayonnaise"]]],
  ["/foods/sriracha.jpg",[["sriracha"]]],
  ["/foods/balsamic_vinaigrette.jpg",[["balsamic vinaigrette"]]],
  ["/foods/italian_dressing.jpg",[["italian dressing"]]],
  ["/foods/caesar_dressing.jpg",[["caesar dressing"]]],
  ["/foods/teriyaki_sauce.jpg",[["teriyaki sauce"]]],
  ["/foods/maple_syrup.jpg",[["maple syrup"]]],
  ["/foods/jam_jelly.jpg",[["jam"], ["jelly"]]],
  ["/foods/nutella.jpg",[["nutella"]]],
  ["/foods/water_glass.jpg",[["water"]]],
  ["/foods/black_coffee.jpg",[["black coffee"]]],
  ["/foods/orange_juice.jpg",[["orange juice"]]],
  ["/foods/coca_cola.jpg",[["coca-cola"]]],
  ["/foods/diet_coke.jpg",[["diet coke"]]],
  ["/foods/gatorade.jpg",[["gatorade"]]],
  ["/foods/almond_milk.jpg",[["almond milk", "unsweetened"]]],
  ["/foods/oat_milk.jpg",[["oat milk"]]],
  ["/foods/gatorade_zero.jpg",[["gatorade zero"]]],
  ["/foods/body_armor_lyte.jpg",[["body armor lyte"]]],
  ["/foods/monster_energy.jpg",[["monster energy", "original"]]],
  ["/foods/monster_zero_ultra.jpg",[["monster", "zero ultra"]]],
  ["/foods/red_bull.jpg",[["red bull", "original"], ["red bull", "8.4"]]],
  ["/foods/red_bull_sugar_free.jpg",[["red bull", "sugar free"]]],
  ["/foods/celsius_sparkling.jpg",[["celsius"]]],
  ["/foods/fairlife_chocolate_shake.jpg",[["fairlife", "chocolate"]]],
  ["/foods/fairlife_vanilla_shake.jpg",[["fairlife", "vanilla"]]],
  ["/foods/premier_protein_chocolate.jpg",[["premier protein", "chocolate"]]],
  ["/foods/premier_protein_vanilla.jpg",[["premier protein", "vanilla"]]],
  ["/foods/muscle_milk_shake.jpg",[["muscle milk"]]],
  ["/foods/powerade_zero.jpg",[["powerade"]]],
  ["/foods/chicken_rice_bowl.jpg",[["chicken", "rice bowl"]]],
  ["/foods/protein_smoothie.jpg",[["protein smoothie"]]],
  ["/foods/turkey_sandwich.jpg",[["turkey sandwich"]]],
  ["/foods/steak_and_potatoes.jpg",[["steak", "potatoes"]]],
  ["/foods/salmon_and_veggies.jpg",[["salmon", "veggies"]]],
  ["/foods/egg_toast_breakfast.jpg",[["egg", "toast"]]],
  ["/foods/overnight_oats.jpg",[["overnight oats"]]],
  ["/foods/tuna_salad.jpg",[["tuna salad"]]],
  ["/foods/burrito_bowl.jpg",[["burrito bowl"]]],
  ["/foods/greek_yogurt_parfait.jpg",[["greek yogurt parfait"]]],
  ["/foods/mcdonalds_big_mac.jpg",[["big mac"]]],
  ["/foods/mcdonalds_quarter_pounder.jpg",[["quarter pounder with cheese"]]],
  ["/foods/mcdonalds_mcchicken.jpg",[["mcchicken"]]],
  ["/foods/mcdonalds_nuggets_4pc.jpg",[["mcnuggets", "4"]]],
  ["/foods/mcdonalds_nuggets_6pc.jpg",[["mcnuggets", "6"]]],
  ["/foods/mcdonalds_nuggets_10pc.jpg",[["mcnuggets", "10"]]],
  ["/foods/mcdonalds_nuggets_20pc.jpg",[["mcnuggets", "20"]]],
  ["/foods/mcdonalds_filet_o_fish.jpg",[["filet-o-fish"]]],
  ["/foods/mcdonalds_mcdouble.jpg",[["mcdouble"]]],
  ["/foods/mcdonalds_egg_mcmuffin.jpg",[["egg mcmuffin"]]],
  ["/foods/mcdonalds_sausage_mcmuffin.jpg",[["sausage mcmuffin"]]],
  ["/foods/mcdonalds_sausage_mcmuffin_egg.jpg",[["sausage mcmuffin with egg"]]],
  ["/foods/mcdonalds_hash_brown.jpg",[["hash brown"], ["mcdonald"]]],
  ["/foods/mcdonalds_large_fries.jpg",[["large fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_medium_fries.jpg",[["medium fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_small_fries.jpg",[["small fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_grilled_chicken_salad.jpg",[["southwest grilled chicken salad"]]],
  ["/foods/mcdonalds_apple_slices.jpg",[["apple slices"]]],
  ["/foods/mcdonalds_mcflurry_oreo.jpg",[["mcflurry", "oreo"]]],
  ["/foods/mcdonalds_mcflurry_mm.jpg",[["mcflurry", "m&m"]]],
  ["/foods/mcdonalds_hotcakes.jpg",[["hotcakes"]]],
  ["/foods/mcdonalds_big_breakfast.jpg",[["big breakfast"]]],
  ["/foods/mcdonalds_bacon_egg_biscuit.jpg",[["bacon egg", "biscuit"]]],
  ["/foods/mcdonalds_iced_coffee.jpg",[["iced coffee"], ["mcdonald"]]],
  ["/foods/mcdonalds_chocolate_shake.jpg",[["chocolate shake"], ["mcdonald"]]],
  ["/foods/mcdonalds_vanilla_shake.jpg",[["vanilla shake"], ["mcdonald"]]],
  ["/foods/mcdonalds_double_quarter_pounder.jpg",[["double quarter pounder"]]],
  ["/foods/mcdonalds_crispy_chicken_sandwich.jpg",[["crispy chicken sandwich"], ["mcdonald"]]],
  ["/foods/chickfila_original_sandwich.jpg",[["original chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_spicy_sandwich.jpg",[["spicy chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_grilled_sandwich.jpg",[["grilled chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_nuggets_8ct.jpg",[["chicken nuggets", "8"], ["chick-fil-a"]]],
  ["/foods/chickfila_nuggets_12ct.jpg",[["chicken nuggets", "12"], ["chick-fil-a"]]],
  ["/foods/chickfila_grilled_nuggets.jpg",[["grilled nuggets"], ["chick-fil-a"]]],
  ["/foods/chickfila_waffle_fries_medium.jpg",[["waffle fries", "medium"]]],
  ["/foods/chickfila_waffle_fries_large.jpg",[["waffle fries", "large"]]],
  ["/foods/chickfila_mac_cheese.jpg",[["mac", "cheese", "medium"], ["chick-fil-a"]]],
  ["/foods/chickfila_chicken_biscuit.jpg",[["chicken biscuit"]]],
  ["/foods/chickfila_spicy_southwest_salad.jpg",[["spicy southwest salad"]]],
  ["/foods/chickfila_grilled_cool_wrap.jpg",[["grilled cool wrap"]]],
  ["/foods/chickfila_chick_n_strips.jpg",[["chick-n-strips"]]],
  ["/foods/chickfila_frosted_lemonade.jpg",[["frosted lemonade"]]],
  ["/foods/chickfila_milkshake.jpg",[["cookies", "cream milkshake"]]],
  ["/foods/chickfila_hash_brown_burrito.jpg",[["hash brown scramble burrito"]]],
  ["/foods/chickfila_tortilla_soup.jpg",[["chicken tortilla soup"]]],
  ["/foods/chickfila_side_salad.jpg",[["side salad"], ["chick-fil-a"]]],
  ["/foods/chickfila_cobb_salad.jpg",[["cobb salad"]]],
  ["/foods/chickfila_fruit_cup.jpg",[["fruit cup"]]],
  ["/foods/chickfila_chocolate_chip_cookie.jpg",[["chocolate chip cookie"], ["chick-fil-a"]]],
  ["/foods/chickfila_sauce.jpg",[["chick-fil-a sauce"]]],
  ["/foods/chipotle_chicken_burrito.jpg",[["chicken burrito"], ["chipotle"]]],
  ["/foods/chipotle_steak_burrito.jpg",[["steak burrito"], ["chipotle"]]],
  ["/foods/chipotle_chicken_bowl.jpg",[["chicken bowl"], ["chipotle"]]],
  ["/foods/chipotle_steak_bowl.jpg",[["steak bowl"], ["chipotle"]]],
  ["/foods/chipotle_carnitas_bowl.jpg",[["carnitas bowl"]]],
  ["/foods/chipotle_sofritas_bowl.jpg",[["sofritas bowl"]]],
  ["/foods/chipotle_chips_guacamole.jpg",[["chips", "guacamole"]]],
  ["/foods/chipotle_chips_queso.jpg",[["chips", "queso"]]],
  ["/foods/chipotle_cilantro_lime_rice.jpg",[["cilantro-lime", "rice"]]],
  ["/foods/chipotle_black_beans.jpg",[["black beans"], ["chipotle"]]],
  ["/foods/chipotle_pinto_beans.jpg",[["pinto beans"], ["chipotle"]]],
  ["/foods/chipotle_chicken_quesadilla.jpg",[["chicken quesadilla"], ["chipotle"]]],
  ["/foods/chipotle_steak_tacos.jpg",[["steak tacos"], ["chipotle"]]],
  ["/foods/chipotle_chicken_tacos.jpg",[["chicken tacos"], ["chipotle"]]],
  ["/foods/chipotle_barbacoa_bowl.jpg",[["barbacoa bowl"]]],
  ["/foods/chipotle_veggie_bowl.jpg",[["veggie bowl"], ["chipotle"]]],
  ["/foods/subway_turkey_6inch.jpg",[["6\"", "turkey breast"], ["6\" turkey breast"]]],
  ["/foods/subway_italian_bmt_6inch.jpg",[["6\"", "italian bmt"], ["6\" italian bmt"]]],
  ["/foods/subway_chicken_teriyaki_6inch.jpg",[["6\"", "chicken teriyaki"], ["6\" chicken teriyaki"]]],
  ["/foods/subway_meatball_marinara_6inch.jpg",[["6\"", "meatball"], ["6\" meatball"]]],
  ["/foods/subway_tuna_6inch.jpg",[["6\"", "tuna"], ["6\" tuna"]]],
  ["/foods/subway_veggie_delite_6inch.jpg",[["6\"", "veggie delite"], ["6\" veggie delite"]]],
  ["/foods/subway_steak_cheese_6inch.jpg",[["6\"", "steak", "cheese"], ["6\" steak", "cheese"]]],
  ["/foods/subway_spicy_italian_6inch.jpg",[["6\"", "spicy italian"], ["6\" spicy italian"]]],
  ["/foods/subway_turkey_footlong.jpg",[["footlong turkey"]]],
  ["/foods/subway_italian_bmt_footlong.jpg",[["footlong italian bmt"]]],
  ["/foods/subway_chicken_teriyaki_footlong.jpg",[["footlong chicken teriyaki"]]],
  ["/foods/subway_chocolate_chip_cookie.jpg",[["chocolate chip cookie"], ["subway"]]],
  ["/foods/subway_rotisserie_chicken_6inch.jpg",[["rotisserie chicken"], ["subway"]]],
  ["/foods/subway_cold_cut_combo_6inch.jpg",[["cold cut combo"]]],
  ["/foods/subway_black_forest_ham_6inch.jpg",[["black forest ham"]]],
  ["/foods/subway_meatball_marinara_footlong.jpg",[["footlong meatball"]]],
  ["/foods/tacobell_crunchy_taco.jpg",[["crunchy taco"]]],
  ["/foods/tacobell_soft_taco.jpg",[["soft taco"]]],
  ["/foods/tacobell_crunchy_taco_supreme.jpg",[["crunchy taco supreme"]]],
  ["/foods/tacobell_burrito_supreme.jpg",[["burrito supreme"]]],
  ["/foods/tacobell_crunchwrap_supreme.jpg",[["crunchwrap supreme"]]],
  ["/foods/tacobell_chicken_quesadilla.jpg",[["chicken quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_steak_quesadilla.jpg",[["steak quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_mexican_pizza.jpg",[["mexican pizza"]]],
  ["/foods/tacobell_nachos_bellgrande.jpg",[["nachos bellgrande"]]],
  ["/foods/tacobell_cheesy_gordita_crunch.jpg",[["cheesy gordita crunch"]]],
  ["/foods/tacobell_bean_burrito.jpg",[["bean burrito"], ["taco bell"]]],
  ["/foods/tacobell_chalupa_supreme.jpg",[["chalupa supreme"]]],
  ["/foods/tacobell_beefy_5layer_burrito.jpg",[["beefy 5-layer"]]],
  ["/foods/tacobell_doritos_locos_taco.jpg",[["doritos locos"]]],
  ["/foods/tacobell_cheese_quesadilla.jpg",[["cheese quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_chicken_burrito.jpg",[["chicken burrito"], ["taco bell"]]],
  ["/foods/tacobell_nachos_cheese.jpg",[["nachos", "cheese"], ["taco bell"]]],
  ["/foods/wendys_daves_single.jpg",[["dave", "single"]]],
  ["/foods/wendys_daves_double.jpg",[["dave", "double"]]],
  ["/foods/wendys_daves_triple.jpg",[["dave", "triple"]]],
  ["/foods/wendys_baconator.jpg",[["baconator"]]],
  ["/foods/wendys_spicy_chicken_sandwich.jpg",[["spicy chicken sandwich"], ["wendy"]]],
  ["/foods/wendys_jr_cheeseburger.jpg",[["jr. cheeseburger"]]],
  ["/foods/wendys_jr_bacon_cheeseburger.jpg",[["jr. bacon cheeseburger"]]],
  ["/foods/wendys_nuggets_4ct.jpg",[["nuggets", "4"], ["wendy"]]],
  ["/foods/wendys_nuggets_10ct.jpg",[["nuggets", "10"], ["wendy"]]],
  ["/foods/wendys_large_fries.jpg",[["large fries"], ["wendy"]]],
  ["/foods/wendys_chili_small.jpg",[["chili", "small"], ["wendy"]]],
  ["/foods/wendys_chili_large.jpg",[["chili", "large"], ["wendy"]]],
  ["/foods/wendys_baked_potato.jpg",[["baked potato", "plain"], ["wendy"]]],
  ["/foods/wendys_frosty_chocolate.jpg",[["frosty", "chocolate"]]],
  ["/foods/wendys_frosty_vanilla.jpg",[["frosty", "vanilla"]]],
  ["/foods/wendys_classic_chicken_sandwich.jpg",[["classic chicken sandwich"], ["wendy"]]],
  ["/foods/bk_whopper.jpg",[["whopper"]]],
  ["/foods/bk_whopper_jr.jpg",[["whopper jr"]]],
  ["/foods/bk_whopper_with_cheese.jpg",[["whopper with cheese"]]],
  ["/foods/bk_original_chicken_sandwich.jpg",[["original chicken sandwich"], ["burger king"]]],
  ["/foods/bk_chicken_fries.jpg",[["chicken fries"]]],
  ["/foods/bk_onion_rings.jpg",[["onion rings"]]],
  ["/foods/bk_bacon_cheeseburger.jpg",[["bacon cheeseburger"], ["burger king"]]],
  ["/foods/bk_double_whopper.jpg",[["double whopper"]]],
  ["/foods/bk_impossible_whopper.jpg",[["impossible whopper"]]],
  ["/foods/bk_french_fries_medium.jpg",[["french fries", "medium"], ["burger king"]]],
  ["/foods/bk_chicken_jr.jpg",[["chicken jr"]]],
  ["/foods/bk_hash_browns.jpg",[["hash browns", "medium"], ["burger king"]]],
  ["/foods/fiveguys_cheeseburger.jpg",[["cheeseburger"], ["five guys"]]],
  ["/foods/fiveguys_little_cheeseburger.jpg",[["little cheeseburger"]]],
  ["/foods/fiveguys_bacon_cheeseburger.jpg",[["bacon cheeseburger"], ["five guys"]]],
  ["/foods/fiveguys_little_bacon_cheeseburger.jpg",[["little bacon cheeseburger"]]],
  ["/foods/fiveguys_cajun_fries.jpg",[["cajun fries"], ["five guys"]]],
  ["/foods/fiveguys_regular_fries.jpg",[["regular fries"], ["five guys"]]],
  ["/foods/fiveguys_hot_dog.jpg",[["hot dog"], ["five guys"]]],
  ["/foods/fiveguys_veggie_sandwich.jpg",[["veggie sandwich"], ["five guys"]]],
  ["/foods/panda_orange_chicken.jpg",[["orange chicken"]]],
  ["/foods/panda_beijing_beef.jpg",[["beijing beef"]]],
  ["/foods/panda_kung_pao_chicken.jpg",[["kung pao chicken"]]],
  ["/foods/panda_broccoli_beef.jpg",[["broccoli beef"]]],
  ["/foods/panda_fried_rice.jpg",[["fried rice"], ["panda"]]],
  ["/foods/panda_chow_mein.jpg",[["chow mein"]]],
  ["/foods/panda_super_greens.jpg",[["super greens"]]],
  ["/foods/panda_string_bean_chicken.jpg",[["string bean chicken"]]],
  ["/foods/panda_teriyaki_chicken.jpg",[["grilled teriyaki chicken"]]],
  ["/foods/panda_honey_walnut_shrimp.jpg",[["honey walnut shrimp"]]],
  ["/foods/panda_mushroom_chicken.jpg",[["mushroom chicken"]]],
  ["/foods/panda_steamed_white_rice.jpg",[["steamed white rice"], ["panda"]]],
  ["/foods/popeyes_classic_chicken_sandwich.jpg",[["classic chicken sandwich"], ["popeyes"]]],
  ["/foods/popeyes_spicy_chicken_sandwich.jpg",[["spicy chicken sandwich"], ["popeyes"]]],
  ["/foods/popeyes_chicken_breast.jpg",[["chicken breast", "mild"], ["popeyes"]]],
  ["/foods/popeyes_chicken_thigh.jpg",[["chicken thigh", "mild"], ["popeyes"]]],
  ["/foods/popeyes_cajun_fries.jpg",[["cajun fries"], ["popeyes"]]],
  ["/foods/popeyes_red_beans_rice.jpg",[["red beans", "rice"]]],
  ["/foods/popeyes_biscuit.jpg",[["biscuit"], ["popeyes"]]],
  ["/foods/popeyes_chicken_tenders.jpg",[["chicken tenders"], ["popeyes"]]],
  ["/foods/popeyes_mashed_potatoes.jpg",[["mashed potatoes", "gravy"]]],
  ["/foods/popeyes_coleslaw.jpg",[["coleslaw"]]],
  ["/foods/starbucks_caramel_frappuccino.jpg",[["caramel frappuccino"]]],
  ["/foods/starbucks_caffe_latte.jpg",[["caff\u00e3\u00a8 latte"], ["caffe latte"]]],
  ["/foods/starbucks_caffe_mocha.jpg",[["caff\u00e3\u00a8 mocha"], ["caffe mocha"]]],
  ["/foods/starbucks_pike_place_coffee.jpg",[["pike place"]]],
  ["/foods/starbucks_iced_caramel_macchiato.jpg",[["iced caramel macchiato"]]],
  ["/foods/starbucks_cake_pop.jpg",[["cake pop"]]],
  ["/foods/starbucks_bacon_gouda_sandwich.jpg",[["bacon gouda"]]],
  ["/foods/starbucks_spinach_feta_wrap.jpg",[["spinach feta"]]],
  ["/foods/starbucks_impossible_sandwich.jpg",[["impossible breakfast sandwich"]]],
  ["/foods/starbucks_butter_croissant.jpg",[["butter croissant"], ["starbucks"]]],
  ["/foods/starbucks_blueberry_muffin.jpg",[["blueberry muffin"], ["starbucks"]]],
  ["/foods/starbucks_banana_nut_bread.jpg",[["banana nut bread"]]],
  ["/foods/starbucks_protein_box.jpg",[["protein box", "eggs"]]],
  ["/foods/starbucks_vanilla_sweet_cream_cold_brew.jpg",[["vanilla sweet cream cold brew"]]],
  ["/foods/starbucks_matcha_latte.jpg",[["matcha latte"]]],
  ["/foods/starbucks_chai_tea_latte.jpg",[["chai tea latte"]]],
  ["/foods/starbucks_double_chocolate_brownie.jpg",[["double chocolate brownie"]]],
  ["/foods/dunkin_iced_coffee_cream_sugar.jpg",[["iced coffee", "cream", "sugar"], ["dunkin"]]],
  ["/foods/dunkin_iced_coffee_black.jpg",[["iced coffee", "black"], ["dunkin"]]],
  ["/foods/dunkin_glazed_donut.jpg",[["glazed donut"]]],
  ["/foods/dunkin_boston_kreme_donut.jpg",[["boston kreme"]]],
  ["/foods/dunkin_chocolate_frosted_donut.jpg",[["chocolate frosted donut"]]],
  ["/foods/dunkin_bacon_egg_cheese_croissant.jpg",[["bacon egg", "cheese croissant"]]],
  ["/foods/dunkin_bacon_egg_cheese_bagel.jpg",[["bacon egg", "cheese", "bagel"]]],
  ["/foods/dunkin_plain_bagel_cream_cheese.jpg",[["plain bagel with cream cheese"]]],
  ["/foods/dunkin_hash_browns.jpg",[["hash browns", "6"], ["dunkin"]]],
  ["/foods/dunkin_munchkins.jpg",[["munchkins"]]],
  ["/foods/dunkin_sausage_egg_cheese_wrap.jpg",[["wake-up wrap"]]],
  ["/foods/dunkin_hot_latte.jpg",[["hot latte"], ["dunkin"]]],
  ["/foods/pizzahut_cheese_pizza_slice.jpg",[["cheese pizza", "slice"], ["pizza hut"]]],
  ["/foods/pizzahut_pepperoni_pizza_slice.jpg",[["pepperoni pizza", "slice"], ["pizza hut"]]],
  ["/foods/pizzahut_supreme_pizza_slice.jpg",[["supreme pizza"], ["pizza hut"]]],
  ["/foods/pizzahut_breadsticks.jpg",[["breadstick"], ["pizza hut"]]],
  ["/foods/pizzahut_garlic_bread.jpg",[["garlic bread"], ["pizza hut"]]],
  ["/foods/pizzahut_bone_out_wings.jpg",[["bone-out wings"]]],
  ["/foods/dominos_cheese_pizza_slice.jpg",[["cheese", "slice"], ["domino"]]],
  ["/foods/dominos_pepperoni_pizza_slice.jpg",[["pepperoni", "slice"], ["domino"]]],
  ["/foods/dominos_cinnamon_bread_twists.jpg",[["cinnamon bread twists"]]],
  ["/foods/dominos_boneless_wings.jpg",[["boneless wings"], ["domino"]]],
  ["/foods/papajohns_cheese_pizza_slice.jpg",[["cheese", "slice"], ["papa john"]]],
  ["/foods/papajohns_pepperoni_pizza_slice.jpg",[["pepperoni", "slice"], ["papa john"]]],
  ["/foods/papajohns_garlic_knots.jpg",[["garlic knots"]]],
  ["/foods/papajohns_breadsticks.jpg",[["breadsticks"], ["papa john"]]],
  ["/foods/olivegarden_chicken_alfredo.jpg",[["chicken alfredo"], ["olive garden"]]],
  ["/foods/olivegarden_tour_of_italy.jpg",[["tour of italy"]]],
  ["/foods/olivegarden_breadstick.jpg",[["breadstick"], ["olive garden"]]],
  ["/foods/olivegarden_house_salad.jpg",[["house salad"], ["olive garden"]]],
  ["/foods/olivegarden_chicken_parmigiana.jpg",[["chicken parmigiana"]]],
  ["/foods/olivegarden_fettuccine_alfredo.jpg",[["fettuccine alfredo"]]],
  ["/foods/applebees_classic_burger.jpg",[["classic burger"], ["applebee"]]],
  ["/foods/applebees_boneless_wings.jpg",[["boneless wings"], ["applebee"]]],
  ["/foods/applebees_chicken_tenders_basket.jpg",[["chicken tenders basket"]]],
  ["/foods/applebees_loaded_fries.jpg",[["loaded fries"]]],
  ["/foods/chilis_oldtimer_burger.jpg",[["oldtimer"]]],
  ["/foods/chilis_chicken_crispers.jpg",[["chicken crispers"]]],
  ["/foods/chilis_baby_back_ribs.jpg",[["baby back ribs"]]],
  ["/foods/chilis_chicken_bacon_ranch_quesadillas.jpg",[["chicken bacon ranch quesadilla"]]],
  ["/foods/chilis_classic_buffalo_wings.jpg",[["classic buffalo wings"]]],
  ["/foods/tgifridays_cajun_shrimp_chicken_pasta.jpg",[["cajun shrimp", "chicken pasta"]]],
  ["/foods/tgifridays_fridays_burger.jpg",[["fridays burger"]]],
  ["/foods/tgifridays_sesame_jack_chicken_strips.jpg",[["sesame jack chicken strips"]]],
  ["/foods/quest_chocolate_chip_cookie_dough.jpg",[["chocolate chip cookie dough"], ["quest"]]],
  ["/foods/quest_birthday_cake.jpg",[["birthday cake"], ["quest"]]],
  ["/foods/rxbar_chocolate_sea_salt.jpg",[["chocolate sea salt"], ["rxbar"]]],
  ["/foods/rxbar_peanut_butter_chocolate.jpg",[["peanut butter chocolate"], ["rxbar"]]],
  ["/foods/onebar_birthday_cake.jpg",[["birthday cake"], ["one bar"]]],
  ["/foods/clifbar_crunchy_peanut_butter.jpg",[["crunchy peanut butter"], ["clif"]]],
  ["/foods/kind_dark_chocolate_nuts.jpg",[["dark chocolate nuts", "sea salt"]]],
  ["/foods/larabar_peanut_butter_chocolate_chip.jpg",[["peanut butter chocolate chip"], ["larabar"]]],
  ["/foods/cheerios.jpg",[["cheerios"]]],
  ["/foods/frosted_flakes.jpg",[["frosted flakes"]]],
  ["/foods/special_k.jpg",[["special k"]]],
  ["/foods/raisin_bran.jpg",[["raisin bran"]]],
  ["/foods/lucky_charms.jpg",[["lucky charms"]]],
  ["/foods/cinnamon_toast_crunch.jpg",[["cinnamon toast crunch"]]],
  ["/foods/honey_nut_cheerios.jpg",[["honey nut cheerios"]]],
  ["/foods/froot_loops.jpg",[["froot loops"]]],
  ["/foods/doritos_nacho_cheese.jpg",[["nacho cheese doritos"]]],
  ["/foods/doritos_cool_ranch.jpg",[["cool ranch doritos"]]],
  ["/foods/cheez_its_original.jpg",[["cheez-it"]]],
  ["/foods/goldfish_cheddar.jpg",[["goldfish"]]],
  ["/foods/hard_pretzels.jpg",[["hard pretzels"]]],
  ["/foods/rice_cakes_lightly_salted.jpg",[["rice cakes"]]],
  ["/foods/movie_theater_popcorn.jpg",[["movie theater popcorn"]]],
  ["/foods/skinny_pop.jpg",[["skinny pop"]]],
  ["/foods/trail_mix.jpg",[["trail mix"]]],
  ["/foods/beef_jerky_original.jpg",[["original beef jerky"]]],
  ["/foods/beef_jerky_teriyaki.jpg",[["teriyaki beef jerky"]]],
  ["/foods/cheddar_sour_cream_chips.jpg",[["cheddar", "sour cream", "chips"]]],
  ["/foods/peanut_butter_crackers.jpg",[["peanut butter crackers"]]],
  ["/foods/veggie_straws_original.jpg",[["veggie straws"]]],
  ["/foods/lean_cuisine_chicken_alfredo.jpg",[["chicken alfredo"], ["lean cuisine"]]],
  ["/foods/lean_cuisine_herb_roasted_chicken.jpg",[["herb roasted chicken"]]],
  ["/foods/healthy_choice_cafe_steamers.jpg",[["caf\u00e3\u00a9 steamers"], ["cafe steamers"]]],
  ["/foods/healthy_choice_power_bowl.jpg",[["power bowl"]]],
  ["/foods/hot_pockets_cheese_pizza.jpg",[["cheese pizza pocket"]]],
  ["/foods/hot_pockets_pepperoni_pizza.jpg",[["pepperoni pizza pocket"]]],
  ["/foods/digiorno_cheese_pizza_slice.jpg",[["digiorno", "cheese"]]],
  ["/foods/digiorno_pepperoni_pizza_slice.jpg",[["digiorno", "pepperoni"]]],
  ["/foods/totinos_pizza_rolls.jpg",[["pizza rolls"]]],
  ["/foods/totinos_party_pizza.jpg",[["party pizza"]]],
  ["/foods/amys_bean_cheese_burrito.jpg",[["burrito", "bean", "cheese"], ["amy"]]],
  ["/foods/amys_cheese_enchilada.jpg",[["cheese enchilada"]]],
  ["/foods/daves_killer_bread_21_grains.jpg",[["21 whole grains"]]],
  ["/foods/daves_killer_bread_good_seed.jpg",[["good seed"]]],
  ["/foods/ezekiel_sprouted_bread.jpg",[["ezekiel"]]],
  ["/foods/english_muffin_whole_wheat.jpg",[["english muffin"]]],
  ["/foods/pita_bread.jpg",[["pita bread"]]],
  ["/foods/naan_bread.jpg",[["naan"]]],
  ["/foods/croissant_large.jpg",[["croissant", "large"]]],
  ["/foods/hamburger_bun.jpg",[["hamburger bun"]]],
  ["/foods/fairlife_2percent_milk.jpg",[["fairlife 2"]]],
  ["/foods/fairlife_fat_free_milk.jpg",[["fairlife fat free"]]],
  ["/foods/chobani_vanilla_greek_yogurt.jpg",[["vanilla greek yogurt", "chobani"]]],
  ["/foods/yoplait_strawberry_yogurt.jpg",[["strawberry yogurt", "yoplait"]]],
  ["/foods/light_string_cheese.jpg",[["string cheese"]]],
  ["/foods/cottage_cheese_4percent.jpg",[["cottage cheese", "4"]]],
  ["/foods/parmesan_cheese_grated.jpg",[["parmesan"]]],
  ["/foods/swiss_cheese_slice.jpg",[["swiss cheese"]]],
  ["/foods/vanilla_ice_cream.jpg",[["vanilla ice cream"]]],
  ["/foods/chocolate_ice_cream.jpg",[["chocolate ice cream"]]],
  ["/foods/frozen_yogurt_vanilla.jpg",[["frozen yogurt", "vanilla"]]],
  ["/foods/brownie_homemade.jpg",[["brownie", "homemade"]]],
  ["/foods/chocolate_chip_cookie_large.jpg",[["chocolate chip cookie", "large"]]],
  ["/foods/cheesecake_slice.jpg",[["cheesecake", "slice"]]],
  ["/foods/apple_pie_slice.jpg",[["apple pie", "slice"]]],
  ["/foods/plain_glazed_donut.jpg",[["plain glazed donut"]]],
  ["/foods/cinnamon_roll_large.jpg",[["cinnamon roll", "large"]]],
  ["/foods/blueberry_muffin_bakery.jpg",[["blueberry muffin", "bakery"]]],
  ["/foods/pancakes_3.jpg",[["pancakes", "plain", "3"]]],
  ["/foods/waffles_2.jpg",[["waffles", "plain", "2"]]],
  ["/foods/french_toast_2_slices.jpg",[["french toast", "2 slices"]]],
  ["/foods/dark_chocolate_70.jpg",[["dark chocolate", "70"]]],
  ["/foods/milk_chocolate.jpg",[["milk chocolate"]]],
  ["/foods/snickers_bar.jpg",[["snickers bar"]]],
  ["/foods/kit_kat_4finger.jpg",[["kit kat"]]],
  ["/foods/reeses_peanut_butter_cups.jpg",[["reese", "s peanut butter cups"]]],
  ["/foods/mms_peanut.jpg",[["m&m", "peanut"]]],
  ["/foods/skittles_original.jpg",[["skittles", "original"]]],
  ["/foods/oreo_cookies_3.jpg",[["oreo", "3"]]],
  ["/foods/chips_ahoy_3.jpg",[["chips ahoy"]]],
  ["/foods/rice_krispies_treat.jpg",[["rice krispies treat"]]],
  ["/foods/pop_tart_frosted_strawberry.jpg",[["pop-tart", "strawberry"]]],
  ["/foods/ben_and_jerrys_chocolate_fudge_brownie.jpg",[["ben", "jerry", "chocolate fudge brownie"]]],
  ["/foods/halo_top_vanilla_bean.jpg",[["halo top", "vanilla bean"]]],
  ["/foods/arroz_blanco.jpg",[["arroz blanco"]]],
  ["/foods/arroz_amarillo.jpg",[["arroz amarillo"]]],
  ["/foods/arroz_con_gandules.jpg",[["arroz con gandules"]]],
  ["/foods/arroz_con_pollo.jpg",[["arroz con pollo"]]],
  ["/foods/arroz_con_habichuelas.jpg",[["arroz con habichuelas"]]],
  ["/foods/arroz_con_salchichas.jpg",[["arroz con salchichas"]]],
  ["/foods/arroz_con_maiz.jpg",[["arroz con ma\u00e3\u00adz"], ["arroz con maiz"]]],
  ["/foods/arroz_mamposteao.jpg",[["mamposteao"]]],
  ["/foods/arroz_con_dulce.jpg",[["arroz con dulce"]]],
  ["/foods/pegao.jpg",[["pegao"]]],
  ["/foods/habichuelas_guisadas_rosadas.jpg",[["habichuelas guisadas", "rosadas"]]],
  ["/foods/habichuelas_guisadas_rojas.jpg",[["habichuelas guisadas", "rojas"]]],
  ["/foods/habichuelas_guisadas_blancas.jpg",[["habichuelas guisadas", "blancas"]]],
  ["/foods/habichuelas_negras_guisadas.jpg",[["habichuelas negras"]]],
  ["/foods/gandules_guisados.jpg",[["gandules guisados"]]],
  ["/foods/pernil.jpg",[["pernil"]]],
  ["/foods/lechon_asado.jpg",[["lech\u00e3\u00b3n asado"], ["lechon asado"]]],
  ["/foods/pollo_guisado.jpg",[["pollo guisado"]]],
  ["/foods/carne_guisada.jpg",[["carne guisada"]]],
  ["/foods/bistec_encebollado.jpg",[["bistec encebollado"]]],
  ["/foods/chuleta_kan_kan.jpg",[["chuleta kan kan"]]],
  ["/foods/churrasco.jpg",[["churrasco"]]],
  ["/foods/pollo_frito.jpg",[["pollo frito"]]],
  ["/foods/pollo_a_la_brasa.jpg",[["pollo a la brasa"]]],
  ["/foods/carne_frita.jpg",[["carne frita"]]],
  ["/foods/chicharron_de_pollo.jpg",[["chicharr\u00e3\u00b3n de pollo"], ["chicharron de pollo"]]],
  ["/foods/chicharron_de_cerdo.jpg",[["chicharr\u00e3\u00b3n de cerdo"], ["chicharron de cerdo"]]],
  ["/foods/camarones_al_ajillo.jpg",[["camarones al ajillo"]]],
  ["/foods/mofongo_relleno_camarones.jpg",[["mofongo", "camarones"]]],
  ["/foods/asopao_de_camarones.jpg",[["asopao de camarones"]]],
  ["/foods/pescado_frito.jpg",[["pescado frito"]]],
  ["/foods/ensalada_de_pulpo.jpg",[["ensalada de pulpo"]]],
  ["/foods/bacalao_guisado.jpg",[["bacalao guisado"]]],
  ["/foods/serenata_de_bacalao.jpg",[["serenata de bacalao"]]],
  ["/foods/mofongo_plain.jpg",[["mofongo"]]],
  ["/foods/mofongo_relleno_pollo.jpg",[["mofongo", "pollo"]]],
  ["/foods/mofongo_relleno_carne.jpg",[["mofongo", "carne"]]],
  ["/foods/tostones.jpg",[["tostones"]]],
  ["/foods/amarillos_maduros.jpg",[["amarillos"], ["maduros"]]],
  ["/foods/trifongo.jpg",[["trifongo"]]],
  ["/foods/mofongo_de_yuca.jpg",[["mofongo de yuca"]]],
  ["/foods/alcapurria_meat.jpg",[["alcapurria", "meat"], ["alcapurria", "carne"]]],
  ["/foods/alcapurria_crab.jpg",[["alcapurria", "crab"], ["alcapurria", "jueyes"]]],
  ["/foods/bacalaito.jpg",[["bacala\u00e3\u00adto"], ["bacalaito"]]],
  ["/foods/empanadilla_carne.jpg",[["empanadilla de carne"]]],
  ["/foods/empanadilla_pollo.jpg",[["empanadilla de pollo"]]],
  ["/foods/empanadilla_pizza.jpg",[["empanadilla de pizza"]]],
  ["/foods/sorullito_de_maiz.jpg",[["sorullito"]]],
  ["/foods/relleno_de_papa.jpg",[["relleno de papa"]]],
  ["/foods/papa_rellena.jpg",[["papa rellena"]]],
  ["/foods/pionono.jpg",[["pionono"]]],
  ["/foods/aranitas_de_platano.jpg",[["ara\u00e3\u00b1itas"], ["aranitas"]]],
  ["/foods/toston_relleno.jpg",[["tost\u00e3\u00b3n relleno"], ["toston relleno"]]],
  ["/foods/sancocho_puertorriqueno.jpg",[["sancocho puertorrique\u00e3\u00b1o"], ["sancocho puertorriqueno"]]],
  ["/foods/asopao_de_pollo.jpg",[["asopao de pollo"]]],
  ["/foods/sopa_de_pollo_fideos.jpg",[["sopa de pollo con fideos"]]],
  ["/foods/sopa_de_platano.jpg",[["sopa de pl\u00e3\u00a1tano"], ["sopa de platano"]]],
  ["/foods/caldo_de_res.jpg",[["caldo de res"]]],
  ["/foods/yuca_hervida.jpg",[["yuca hervida"]]],
  ["/foods/yuca_frita.jpg",[["yuca frita"]]],
  ["/foods/batata_boniato.jpg",[["batata"], ["boniato"]]],
  ["/foods/guineo_verde_hervido.jpg",[["guineo verde"]]],
  ["/foods/platano_hervido.jpg",[["pl\u00e3\u00a1tano hervido"], ["platano hervido"]]],
  ["/foods/ensalada_de_coditos.jpg",[["ensalada de coditos"]]],
  ["/foods/ensalada_de_papa.jpg",[["ensalada de papa"]]],
  ["/foods/pastelon_de_platano_maduro.jpg",[["pastel\u00e3\u00b3n"], ["pastelon"]]],
  ["/foods/pasteles_pork.jpg",[["pasteles", "pork"], ["pasteles", "cerdo"]]],
  ["/foods/pasteles_de_yuca.jpg",[["pasteles de yuca"]]],
  ["/foods/lasagna_boricua.jpg",[["lasagna boricua"]]],
  ["/foods/huevos_revueltos_jamon.jpg",[["huevos revueltos"]]],
  ["/foods/tortilla_de_huevo.jpg",[["tortilla de huevo"]]],
  ["/foods/avena_pr.jpg",[["avena"]]],
  ["/foods/pan_sobao.jpg",[["pan sobao"]]],
  ["/foods/pan_de_agua.jpg",[["pan de agua"]]],
  ["/foods/mallorca_bread.jpg",[["mallorca"]]],
  ["/foods/mallorca_jamon_queso.jpg",[["mallorca", "jam\u00e3\u00b3n"], ["mallorca", "jamon"]]],
  ["/foods/quesito.jpg",[["quesito"]]],
  ["/foods/pastelillo_de_guayaba.jpg",[["pastelillo de guayaba"]]],
  ["/foods/pastelillo_guayaba_queso.jpg",[["pastelillo", "guayaba", "queso"]]],
  ["/foods/tembleque.jpg",[["tembleque"]]],
  ["/foods/flan_de_queso.jpg",[["flan de queso"]]],
  ["/foods/flan_de_coco.jpg",[["flan de coco"]]],
  ["/foods/tres_leches_cake.jpg",[["tres leches"]]],
  ["/foods/limber_de_coco.jpg",[["limber de coco"]]],
  ["/foods/piragua.jpg",[["piragua"]]],
  ["/foods/cafe_con_leche.jpg",[["caf\u00e3\u00a9 con leche"], ["cafe con leche"]]],
  ["/foods/cafe_puya.jpg",[["caf\u00e3\u00a9 puya"], ["cafe puya"]]],
  ["/foods/malta_india.jpg",[["malta india"]]],
  ["/foods/coquito.jpg",[["coquito"]]],
  ["/foods/jugo_de_parcha.jpg",[["jugo de parcha"]]],
  ["/foods/jugo_de_guayaba.jpg",[["jugo de guayaba"]]],
  ["/foods/pina_colada.jpg",[["pi\u00e3\u00b1a colada"], ["pina colada"]]],
  ["/foods/polloTropical_tropichop.jpg",[["tropichop"]]],
  ["/foods/polloTropical_quarter_chicken_dark.jpg",[["quarter chicken", "dark"], ["pollo tropical"]]],
  ["/foods/polloTropical_quarter_chicken_white.jpg",[["quarter chicken", "white"], ["pollo tropical"]]],
  ["/foods/polloTropical_moro_rice.jpg",[["moro rice"]]],
  ["/foods/polloTropical_sweet_plantains.jpg",[["sweet plantains"], ["pollo tropical"]]],
  ["/foods/pica_pollo.jpg",[["pica pollo"]]],
  ["/foods/yaroa_de_pollo.jpg",[["yaroa"]]],
  ["/foods/mangu.jpg",[["mang\u00e3\u00ba"], ["mangu"]]],
  ["/foods/tres_golpes.jpg",[["tres golpes"]]],
  ["/foods/sancocho_dominicano.jpg",[["sancocho dominicano"]]],
  ["/foods/chimichurri_burger.jpg",[["chimichurri burger"]]],
  ["/foods/moro_habichuelas_negras.jpg",[["moro de habichuelas negras"]]],
  ["/foods/moro_gandules.jpg",[["moro de gandules"]]],
  ["/foods/habichuela_con_dulce.jpg",[["habichuela con dulce"]]],
  ["/foods/concon.jpg",[["conc\u00e3\u00b3n"], ["concon"]]],
  ["/foods/chofan.jpg",[["chof\u00e3\u00a1n"], ["chofan"]]],
  ["/foods/cubano_sandwich.jpg",[["cubano sandwich"]]],
  ["/foods/ropa_vieja.jpg",[["ropa vieja"]]],
  ["/foods/vaca_frita.jpg",[["vaca frita"]]],
  ["/foods/medianoche_sandwich.jpg",[["medianoche"]]],
  ["/foods/croquetas_de_jamon.jpg",[["croquetas de jam\u00e3\u00b3n"], ["croquetas de jamon"]]],
  ["/foods/california_roll.jpg",[["california roll"]]],
  ["/foods/spicy_tuna_roll.jpg",[["spicy tuna roll"]]],
  ["/foods/salmon_roll.jpg",[["salmon roll"]]],
  ["/foods/pad_thai_chicken.jpg",[["pad thai", "chicken"]]],
  ["/foods/fried_rice_takeout.jpg",[["fried rice", "takeout"]]],
  ["/foods/lo_mein_chicken.jpg",[["lo mein", "chicken"]]],
  ["/foods/general_tsos_chicken.jpg",[["general tso"]]],
  ["/foods/chicken_tikka_masala.jpg",[["chicken tikka masala"]]],
  ["/foods/falafel.jpg",[["falafel"]]],
  ["/foods/chicken_shawarma_wrap.jpg",[["chicken shawarma"]]],
  ["/foods/gyro_lamb_beef.jpg",[["gyro"]]],
  ["/foods/pho_beef.jpg",[["pho"]]],
  ["/foods/instant_ramen.jpg",[["instant ramen"]]],
  ["/foods/restaurant_ramen_tonkotsu.jpg",[["ramen", "tonkotsu"]]],
  ["/foods/bibimbap.jpg",[["bibimbap"]]],
  ["/foods/pork_tamale.jpg",[["pork tamale"]]],
  ["/foods/beef_empanada.jpg",[["beef empanada"]]],
  ["/foods/pupusa_cheese.jpg",[["pupusa"]]],
  ["/foods/jerk_chicken_thigh.jpg",[["jerk chicken"]]],
  ["/foods/chicken_curry_thai_green.jpg",[["thai green", "curry"], ["chicken curry", "thai"]]],
  ["/foods/chicken_curry_japanese.jpg",[["japanese", "curry"], ["chicken curry", "japanese"]]],
  ["/foods/pork_dumplings_steamed.jpg",[["pork dumplings", "steamed"]]],
  ["/foods/pork_dumplings_fried.jpg",[["pork dumplings", "fried"]]],
  ["/foods/vegetable_spring_rolls.jpg",[["vegetable spring rolls"]]],
  ["/foods/pork_egg_rolls.jpg",[["pork egg rolls"]]],
  ["/foods/arepas_cheese.jpg",[["arepas", "cheese"]]],
  ["/foods/chicken_teriyaki_bowl.jpg",[["chicken teriyaki bowl"]]],
  ["/foods/butter_chicken.jpg",[["butter chicken"]]],
  ["/foods/lamb_curry_vindaloo.jpg",[["lamb", "vindaloo"]]],
  ["/foods/vegetable_samosa.jpg",[["vegetable samosa"]]],
  ["/foods/chicken_satay.jpg",[["chicken satay"]]],
  ["/foods/innout_double_double.jpg",[["double-double"]]],
  ["/foods/innout_cheeseburger_protein_style.jpg",[["protein style"], ["in-n-out"]]],
  ["/foods/innout_animal_style_fries.jpg",[["animal style fries"]]],
  ["/foods/deltaco_crunchy_taco.jpg",[["crunchy taco"], ["del taco"]]],
  ["/foods/whitecastle_original_slider.jpg",[["original slider"], ["white castle"]]],
  ["/foods/mcdonalds_6pc_nuggets_meal.jpg",[["6pc", "mcnuggets", "meal"], ["6 piece", "mcnuggets", "medium", "meal"]]],
  ["/foods/mcdonalds_bacon_clubhouse_burger.jpg",[["bacon clubhouse"]]],
  ["/foods/mcdonalds_grilled_chicken_deluxe.jpg",[["grilled chicken deluxe"]]],
  ["/foods/qdoba_chicken_burrito_bowl.jpg",[["chicken burrito bowl"], ["qdoba"]]],
  ["/foods/arbys_original_roast_beef.jpg",[["original roast beef"], ["arby"]]],
  // Fallback mappings for items without dedicated images
  ["/foods/whey_protein_shake.jpg",[["creatine monohydrate"], ["bcaa powder"]]],
  ["/foods/olive_oil.jpg",[["cooking spray"], ["pam"]]],
  ["/foods/asopao_de_pollo.jpg",[["sopa de salchich"]]],
  ["/foods/tembleque.jpg",[["majarete"]]],
  ["/foods/pancakes_3.jpg",[["panqueques con sirope"]]],
  ["/foods/tres_leches_cake.jpg",[["bizcocho de ron"]]],
  ["/foods/quesito.jpg",[["mantecaditos"], ["polvor"]]],
  ["/foods/limber_de_coco.jpg",[["limber de parcha"]]],
  ["/foods/tembleque.jpg",[["dulce de lechoza"], ["besitos de coco"]]],
  ["/foods/arroz_con_dulce.jpg",[["arroz con coco"]]],
  ["/foods/jugo_de_guayaba.jpg",[["jugo de acerola"]]],
  ["/foods/pina_colada.jpg",[["morir so"]]],
  ["/foods/malta_india.jpg",[["medalla light"]]],
  ["/foods/empanadilla_pollo.jpg",[["pastelitos dominicanos"]]],
  ["/foods/beef_empanada.jpg",[["empanada de carne"]]],
  ["/foods/arepas_cheese.jpg",[["arepas de queso"]]],
];

const cache = new Map();

export function getFoodImage(name, brand) {
  if (!name) return null;
  const key = brand ? `${name}||${brand}` : name;
  const c = cache.get(key);
  if (c !== undefined) return c;
  // Search against combined "brand name" so branded items match patterns like "chick-fil-a" + "nuggets"
  const l = brand ? `${brand} ${name}`.toLowerCase() : name.toLowerCase();
  for (const [img, pats] of R) {
    for (const parts of pats) {
      if (parts.every(p => l.includes(p))) { const url = foodImageUrl(img); cache.set(key, url); return url; }
    }
  }
  // Fallback: try name-only match (for non-branded items)
  if (brand) {
    const nameOnly = name.toLowerCase();
    for (const [img, pats] of R) {
      for (const parts of pats) {
        if (parts.every(p => nameOnly.includes(p))) { const url = foodImageUrl(img); cache.set(key, url); return url; }
      }
    }
  }
  cache.set(key, null);
  return null;
}
