// Auto-generated from 0063_ai_food_images.sql
// Maps food name patterns to image paths
// 646 rules

const R = [
  ["/foods/chicken_breast.png",[["chicken breast"], ["pechuga de pollo"]]],
  ["/foods/chicken_thigh.png",[["chicken thigh"], ["muslo de pollo"]]],
  ["/foods/ground_turkey.png",[["ground turkey"]]],
  ["/foods/ground_beef_90.png",[["ground beef", "90"], ["ground beef (90"]]],
  ["/foods/ground_beef_80.png",[["ground beef", "80"], ["ground beef (80"]]],
  ["/foods/salmon_fillet.png",[["salmon fillet"], ["salmon", "cooked"]]],
  ["/foods/tuna_canned.png",[["tuna", "canned"], ["tuna", "water"], ["at\u00e3\u00ban"]]],
  ["/foods/shrimp_cooked.png",[["shrimp", "cooked"]]],
  ["/foods/tilapia_cooked.png",[["tilapia"]]],
  ["/foods/pork_tenderloin.png",[["pork tenderloin"]]],
  ["/foods/steak_sirloin.png",[["sirloin"]]],
  ["/foods/steak_ribeye.png",[["ribeye"]]],
  ["/foods/turkey_breast_deli.png",[["turkey breast", "deli"]]],
  ["/foods/bacon_cooked.png",[["bacon", "cooked"], ["bacon"]]],
  ["/foods/sausage_link.png",[["sausage link"]]],
  ["/foods/cod_baked.png",[["cod", "baked"]]],
  ["/foods/halibut_baked.png",[["halibut"]]],
  ["/foods/sardines_canned.png",[["sardine"]]],
  ["/foods/catfish_baked.png",[["catfish"]]],
  ["/foods/mahi_mahi.png",[["mahi"]]],
  ["/foods/crab_meat.png",[["crab"]]],
  ["/foods/lobster_steamed.png",[["lobster"]]],
  ["/foods/beef_brisket.png",[["brisket"]]],
  ["/foods/lamb_chop.png",[["lamb chop"]]],
  ["/foods/veal_cutlet.png",[["veal"]]],
  ["/foods/turkey_burger.png",[["turkey burger"]]],
  ["/foods/bison_burger.png",[["bison"]]],
  ["/foods/venison_roasted.png",[["venison"]]],
  ["/foods/pork_chop.png",[["pork chop"]]],
  ["/foods/lamb_ground.png",[["lamb", "ground"]]],
  ["/foods/egg_whole.png",[["egg", "large"], ["egg (whole, large)"]]],
  ["/foods/egg_white.png",[["egg white"]]],
  ["/foods/greek_yogurt_0.png",[["greek yogurt", "0"]]],
  ["/foods/greek_yogurt_2.png",[["greek yogurt", "2"]]],
  ["/foods/cottage_cheese_2.png",[["cottage cheese", "2"]]],
  ["/foods/milk_whole.png",[["milk (whole)"]]],
  ["/foods/milk_2percent.png",[["milk (2%)"]]],
  ["/foods/milk_skim.png",[["milk (skim)"]]],
  ["/foods/cheese_cheddar.png",[["cheddar"]]],
  ["/foods/cheese_mozzarella.png",[["mozzarella"]]],
  ["/foods/butter.png",[["butter"]]],
  ["/foods/cream_cheese.png",[["cream cheese"]]],
  ["/foods/white_rice.png",[["white rice", "cooked"]]],
  ["/foods/brown_rice.png",[["brown rice"]]],
  ["/foods/jasmine_rice.png",[["jasmine rice"]]],
  ["/foods/quinoa.png",[["quinoa"]]],
  ["/foods/pasta_cooked.png",[["pasta (cooked)"]]],
  ["/foods/bread_white.png",[["bread", "white"], ["bread \u00e2\u20ac\u201d white"]]],
  ["/foods/bread_whole_wheat.png",[["bread", "whole wheat"], ["bread \u00e2\u20ac\u201d whole wheat"]]],
  ["/foods/tortilla_flour.png",[["tortilla", "flour"]]],
  ["/foods/tortilla_corn.png",[["tortilla", "corn"]]],
  ["/foods/oatmeal.png",[["oatmeal", "dry"]]],
  ["/foods/bagel_plain.png",[["bagel", "plain"]]],
  ["/foods/potato_baked.png",[["potato", "baked", "medium"]]],
  ["/foods/sweet_potato_baked.png",[["sweet potato", "baked"]]],
  ["/foods/couscous.png",[["couscous"]]],
  ["/foods/bulgur_wheat.png",[["bulgur"]]],
  ["/foods/farro.png",[["farro"]]],
  ["/foods/barley.png",[["barley"]]],
  ["/foods/wild_rice.png",[["wild rice"]]],
  ["/foods/banana.png",[["banana"]]],
  ["/foods/apple.png",[["apple"]]],
  ["/foods/orange.png",[["orange"]]],
  ["/foods/blueberries.png",[["blueberries"]]],
  ["/foods/strawberries.png",[["strawberries"]]],
  ["/foods/grapes.png",[["grapes"]]],
  ["/foods/avocado.png",[["avocado"]]],
  ["/foods/mango.png",[["mango"]]],
  ["/foods/watermelon.png",[["watermelon"]]],
  ["/foods/pineapple.png",[["pineapple"]]],
  ["/foods/peach.png",[["peach"]]],
  ["/foods/plum.png",[["plum"]]],
  ["/foods/kiwi.png",[["kiwi"]]],
  ["/foods/pomegranate_seeds.png",[["pomegranate"]]],
  ["/foods/figs_fresh.png",[["figs", "fresh"]]],
  ["/foods/dates_medjool.png",[["dates", "medjool"]]],
  ["/foods/dried_cranberries.png",[["dried cranberries"]]],
  ["/foods/raisins.png",[["raisins"]]],
  ["/foods/raspberries.png",[["raspberries"]]],
  ["/foods/blackberries.png",[["blackberries"]]],
  ["/foods/cantaloupe.png",[["cantaloupe"]]],
  ["/foods/honeydew.png",[["honeydew"]]],
  ["/foods/broccoli.png",[["broccoli", "cooked"]]],
  ["/foods/spinach_raw.png",[["spinach", "raw"]]],
  ["/foods/mixed_salad_greens.png",[["mixed salad"], ["salad greens"]]],
  ["/foods/carrots_raw.png",[["carrots", "raw"], ["carrots (raw)"]]],
  ["/foods/bell_pepper.png",[["bell pepper"]]],
  ["/foods/tomato.png",[["tomato"]]],
  ["/foods/cucumber.png",[["cucumber"]]],
  ["/foods/green_beans.png",[["green beans"]]],
  ["/foods/asparagus.png",[["asparagus"]]],
  ["/foods/corn_cooked.png",[["corn", "cooked"]]],
  ["/foods/mushrooms_raw.png",[["mushrooms", "raw"]]],
  ["/foods/onion_raw.png",[["onion", "raw"]]],
  ["/foods/zucchini_cooked.png",[["zucchini"]]],
  ["/foods/kale_raw.png",[["kale"]]],
  ["/foods/cauliflower_raw.png",[["cauliflower"]]],
  ["/foods/brussels_sprouts.png",[["brussels"]]],
  ["/foods/eggplant_cooked.png",[["eggplant"]]],
  ["/foods/artichoke_cooked.png",[["artichoke"]]],
  ["/foods/beets_cooked.png",[["beets"]]],
  ["/foods/cabbage_raw.png",[["cabbage"]]],
  ["/foods/celery_raw.png",[["celery"]]],
  ["/foods/radishes_raw.png",[["radish"]]],
  ["/foods/snap_peas_raw.png",[["snap peas"]]],
  ["/foods/black_beans.png",[["black beans", "cooked"]]],
  ["/foods/chickpeas.png",[["chickpeas"]]],
  ["/foods/lentils.png",[["lentils"]]],
  ["/foods/peanut_butter.png",[["peanut butter"]]],
  ["/foods/almond_butter.png",[["almond butter"]]],
  ["/foods/almonds.png",[["almonds"]]],
  ["/foods/walnuts.png",[["walnuts"]]],
  ["/foods/cashews.png",[["cashews"]]],
  ["/foods/mixed_nuts.png",[["mixed nuts"]]],
  ["/foods/pistachios.png",[["pistachios"]]],
  ["/foods/macadamia_nuts.png",[["macadamia"]]],
  ["/foods/pecans.png",[["pecans"]]],
  ["/foods/pine_nuts.png",[["pine nuts"]]],
  ["/foods/sunflower_seeds.png",[["sunflower seeds"]]],
  ["/foods/pumpkin_seeds.png",[["pumpkin seeds"]]],
  ["/foods/chia_seeds.png",[["chia seeds"]]],
  ["/foods/flax_seeds.png",[["flax"]]],
  ["/foods/hemp_hearts.png",[["hemp"]]],
  ["/foods/tahini.png",[["tahini"]]],
  ["/foods/kidney_beans.png",[["kidney beans"]]],
  ["/foods/pinto_beans.png",[["pinto beans"]]],
  ["/foods/navy_beans.png",[["navy beans"]]],
  ["/foods/refried_beans.png",[["refried beans"]]],
  ["/foods/tofu_firm.png",[["tofu"]]],
  ["/foods/tempeh.png",[["tempeh"]]],
  ["/foods/seitan.png",[["seitan"]]],
  ["/foods/edamame.png",[["edamame"]]],
  ["/foods/beyond_meat_burger.png",[["beyond meat"]]],
  ["/foods/impossible_burger.png",[["impossible burger patty"]]],
  ["/foods/whey_protein_shake.png",[["whey protein"]]],
  ["/foods/casein_protein_shake.png",[["casein protein"]]],
  ["/foods/mass_gainer_shake.png",[["mass gainer"]]],
  ["/foods/protein_bar.png",[["protein bar", "average"]]],
  ["/foods/olive_oil.png",[["olive oil"]]],
  ["/foods/coconut_oil.png",[["coconut oil"]]],
  ["/foods/honey.png",[["honey"]]],
  ["/foods/soy_sauce.png",[["soy sauce"]]],
  ["/foods/hot_sauce.png",[["hot sauce"]]],
  ["/foods/ketchup.png",[["ketchup"]]],
  ["/foods/mustard.png",[["mustard"]]],
  ["/foods/ranch_dressing.png",[["ranch dressing"]]],
  ["/foods/salsa.png",[["salsa"]]],
  ["/foods/hummus.png",[["hummus"]]],
  ["/foods/guacamole.png",[["guacamole"]]],
  ["/foods/bbq_sauce.png",[["bbq sauce"]]],
  ["/foods/mayonnaise.png",[["mayonnaise"]]],
  ["/foods/sriracha.png",[["sriracha"]]],
  ["/foods/balsamic_vinaigrette.png",[["balsamic vinaigrette"]]],
  ["/foods/italian_dressing.png",[["italian dressing"]]],
  ["/foods/caesar_dressing.png",[["caesar dressing"]]],
  ["/foods/teriyaki_sauce.png",[["teriyaki sauce"]]],
  ["/foods/maple_syrup.png",[["maple syrup"]]],
  ["/foods/jam_jelly.png",[["jam"], ["jelly"]]],
  ["/foods/nutella.png",[["nutella"]]],
  ["/foods/water_glass.png",[["water"]]],
  ["/foods/black_coffee.png",[["black coffee"]]],
  ["/foods/orange_juice.png",[["orange juice"]]],
  ["/foods/coca_cola.png",[["coca-cola"]]],
  ["/foods/diet_coke.png",[["diet coke"]]],
  ["/foods/gatorade.png",[["gatorade"]]],
  ["/foods/almond_milk.png",[["almond milk", "unsweetened"]]],
  ["/foods/oat_milk.png",[["oat milk"]]],
  ["/foods/gatorade_zero.png",[["gatorade zero"]]],
  ["/foods/body_armor_lyte.png",[["body armor lyte"]]],
  ["/foods/monster_energy.png",[["monster energy", "original"]]],
  ["/foods/monster_zero_ultra.png",[["monster", "zero ultra"]]],
  ["/foods/red_bull.png",[["red bull", "original"], ["red bull", "8.4"]]],
  ["/foods/red_bull_sugar_free.png",[["red bull", "sugar free"]]],
  ["/foods/celsius_sparkling.png",[["celsius"]]],
  ["/foods/fairlife_chocolate_shake.png",[["fairlife", "chocolate"]]],
  ["/foods/fairlife_vanilla_shake.png",[["fairlife", "vanilla"]]],
  ["/foods/premier_protein_chocolate.png",[["premier protein", "chocolate"]]],
  ["/foods/premier_protein_vanilla.png",[["premier protein", "vanilla"]]],
  ["/foods/muscle_milk_shake.png",[["muscle milk"]]],
  ["/foods/powerade_zero.png",[["powerade"]]],
  ["/foods/chicken_rice_bowl.png",[["chicken", "rice bowl"]]],
  ["/foods/protein_smoothie.png",[["protein smoothie"]]],
  ["/foods/turkey_sandwich.png",[["turkey sandwich"]]],
  ["/foods/steak_and_potatoes.png",[["steak", "potatoes"]]],
  ["/foods/salmon_and_veggies.png",[["salmon", "veggies"]]],
  ["/foods/egg_toast_breakfast.png",[["egg", "toast"]]],
  ["/foods/overnight_oats.png",[["overnight oats"]]],
  ["/foods/tuna_salad.png",[["tuna salad"]]],
  ["/foods/burrito_bowl.png",[["burrito bowl"]]],
  ["/foods/greek_yogurt_parfait.png",[["greek yogurt parfait"]]],
  ["/foods/mcdonalds_big_mac.png",[["big mac"]]],
  ["/foods/mcdonalds_quarter_pounder.png",[["quarter pounder with cheese"]]],
  ["/foods/mcdonalds_mcchicken.png",[["mcchicken"]]],
  ["/foods/mcdonalds_nuggets_4pc.png",[["mcnuggets", "4"]]],
  ["/foods/mcdonalds_nuggets_6pc.png",[["mcnuggets", "6"]]],
  ["/foods/mcdonalds_nuggets_10pc.png",[["mcnuggets", "10"]]],
  ["/foods/mcdonalds_nuggets_20pc.png",[["mcnuggets", "20"]]],
  ["/foods/mcdonalds_filet_o_fish.png",[["filet-o-fish"]]],
  ["/foods/mcdonalds_mcdouble.png",[["mcdouble"]]],
  ["/foods/mcdonalds_egg_mcmuffin.png",[["egg mcmuffin"]]],
  ["/foods/mcdonalds_sausage_mcmuffin.png",[["sausage mcmuffin"]]],
  ["/foods/mcdonalds_sausage_mcmuffin_egg.png",[["sausage mcmuffin with egg"]]],
  ["/foods/mcdonalds_hash_brown.png",[["hash brown"], ["mcdonald"]]],
  ["/foods/mcdonalds_large_fries.png",[["large fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_medium_fries.png",[["medium fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_small_fries.png",[["small fries"], ["mcdonald"]]],
  ["/foods/mcdonalds_grilled_chicken_salad.png",[["southwest grilled chicken salad"]]],
  ["/foods/mcdonalds_apple_slices.png",[["apple slices"]]],
  ["/foods/mcdonalds_mcflurry_oreo.png",[["mcflurry", "oreo"]]],
  ["/foods/mcdonalds_mcflurry_mm.png",[["mcflurry", "m&m"]]],
  ["/foods/mcdonalds_hotcakes.png",[["hotcakes"]]],
  ["/foods/mcdonalds_big_breakfast.png",[["big breakfast"]]],
  ["/foods/mcdonalds_bacon_egg_biscuit.png",[["bacon egg", "biscuit"]]],
  ["/foods/mcdonalds_iced_coffee.png",[["iced coffee"], ["mcdonald"]]],
  ["/foods/mcdonalds_chocolate_shake.png",[["chocolate shake"], ["mcdonald"]]],
  ["/foods/mcdonalds_vanilla_shake.png",[["vanilla shake"], ["mcdonald"]]],
  ["/foods/mcdonalds_double_quarter_pounder.png",[["double quarter pounder"]]],
  ["/foods/mcdonalds_crispy_chicken_sandwich.png",[["crispy chicken sandwich"], ["mcdonald"]]],
  ["/foods/chickfila_original_sandwich.png",[["original chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_spicy_sandwich.png",[["spicy chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_grilled_sandwich.png",[["grilled chicken sandwich"], ["chick-fil-a"]]],
  ["/foods/chickfila_nuggets_8ct.png",[["chicken nuggets", "8"], ["chick-fil-a"]]],
  ["/foods/chickfila_nuggets_12ct.png",[["chicken nuggets", "12"], ["chick-fil-a"]]],
  ["/foods/chickfila_grilled_nuggets.png",[["grilled nuggets"], ["chick-fil-a"]]],
  ["/foods/chickfila_waffle_fries_medium.png",[["waffle fries", "medium"]]],
  ["/foods/chickfila_waffle_fries_large.png",[["waffle fries", "large"]]],
  ["/foods/chickfila_mac_cheese.png",[["mac", "cheese", "medium"], ["chick-fil-a"]]],
  ["/foods/chickfila_chicken_biscuit.png",[["chicken biscuit"]]],
  ["/foods/chickfila_spicy_southwest_salad.png",[["spicy southwest salad"]]],
  ["/foods/chickfila_grilled_cool_wrap.png",[["grilled cool wrap"]]],
  ["/foods/chickfila_chick_n_strips.png",[["chick-n-strips"]]],
  ["/foods/chickfila_frosted_lemonade.png",[["frosted lemonade"]]],
  ["/foods/chickfila_milkshake.png",[["cookies", "cream milkshake"]]],
  ["/foods/chickfila_hash_brown_burrito.png",[["hash brown scramble burrito"]]],
  ["/foods/chickfila_tortilla_soup.png",[["chicken tortilla soup"]]],
  ["/foods/chickfila_side_salad.png",[["side salad"], ["chick-fil-a"]]],
  ["/foods/chickfila_cobb_salad.png",[["cobb salad"]]],
  ["/foods/chickfila_fruit_cup.png",[["fruit cup"]]],
  ["/foods/chickfila_chocolate_chip_cookie.png",[["chocolate chip cookie"], ["chick-fil-a"]]],
  ["/foods/chickfila_sauce.png",[["chick-fil-a sauce"]]],
  ["/foods/chipotle_chicken_burrito.png",[["chicken burrito"], ["chipotle"]]],
  ["/foods/chipotle_steak_burrito.png",[["steak burrito"], ["chipotle"]]],
  ["/foods/chipotle_chicken_bowl.png",[["chicken bowl"], ["chipotle"]]],
  ["/foods/chipotle_steak_bowl.png",[["steak bowl"], ["chipotle"]]],
  ["/foods/chipotle_carnitas_bowl.png",[["carnitas bowl"]]],
  ["/foods/chipotle_sofritas_bowl.png",[["sofritas bowl"]]],
  ["/foods/chipotle_chips_guacamole.png",[["chips", "guacamole"]]],
  ["/foods/chipotle_chips_queso.png",[["chips", "queso"]]],
  ["/foods/chipotle_cilantro_lime_rice.png",[["cilantro-lime", "rice"]]],
  ["/foods/chipotle_black_beans.png",[["black beans"], ["chipotle"]]],
  ["/foods/chipotle_pinto_beans.png",[["pinto beans"], ["chipotle"]]],
  ["/foods/chipotle_chicken_quesadilla.png",[["chicken quesadilla"], ["chipotle"]]],
  ["/foods/chipotle_steak_tacos.png",[["steak tacos"], ["chipotle"]]],
  ["/foods/chipotle_chicken_tacos.png",[["chicken tacos"], ["chipotle"]]],
  ["/foods/chipotle_barbacoa_bowl.png",[["barbacoa bowl"]]],
  ["/foods/chipotle_veggie_bowl.png",[["veggie bowl"], ["chipotle"]]],
  ["/foods/subway_turkey_6inch.png",[["6\"", "turkey breast"], ["6\" turkey breast"]]],
  ["/foods/subway_italian_bmt_6inch.png",[["6\"", "italian bmt"], ["6\" italian bmt"]]],
  ["/foods/subway_chicken_teriyaki_6inch.png",[["6\"", "chicken teriyaki"], ["6\" chicken teriyaki"]]],
  ["/foods/subway_meatball_marinara_6inch.png",[["6\"", "meatball"], ["6\" meatball"]]],
  ["/foods/subway_tuna_6inch.png",[["6\"", "tuna"], ["6\" tuna"]]],
  ["/foods/subway_veggie_delite_6inch.png",[["6\"", "veggie delite"], ["6\" veggie delite"]]],
  ["/foods/subway_steak_cheese_6inch.png",[["6\"", "steak", "cheese"], ["6\" steak", "cheese"]]],
  ["/foods/subway_spicy_italian_6inch.png",[["6\"", "spicy italian"], ["6\" spicy italian"]]],
  ["/foods/subway_turkey_footlong.png",[["footlong turkey"]]],
  ["/foods/subway_italian_bmt_footlong.png",[["footlong italian bmt"]]],
  ["/foods/subway_chicken_teriyaki_footlong.png",[["footlong chicken teriyaki"]]],
  ["/foods/subway_chocolate_chip_cookie.png",[["chocolate chip cookie"], ["subway"]]],
  ["/foods/subway_rotisserie_chicken_6inch.png",[["rotisserie chicken"], ["subway"]]],
  ["/foods/subway_cold_cut_combo_6inch.png",[["cold cut combo"]]],
  ["/foods/subway_black_forest_ham_6inch.png",[["black forest ham"]]],
  ["/foods/subway_meatball_marinara_footlong.png",[["footlong meatball"]]],
  ["/foods/tacobell_crunchy_taco.png",[["crunchy taco"]]],
  ["/foods/tacobell_soft_taco.png",[["soft taco"]]],
  ["/foods/tacobell_crunchy_taco_supreme.png",[["crunchy taco supreme"]]],
  ["/foods/tacobell_burrito_supreme.png",[["burrito supreme"]]],
  ["/foods/tacobell_crunchwrap_supreme.png",[["crunchwrap supreme"]]],
  ["/foods/tacobell_chicken_quesadilla.png",[["chicken quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_steak_quesadilla.png",[["steak quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_mexican_pizza.png",[["mexican pizza"]]],
  ["/foods/tacobell_nachos_bellgrande.png",[["nachos bellgrande"]]],
  ["/foods/tacobell_cheesy_gordita_crunch.png",[["cheesy gordita crunch"]]],
  ["/foods/tacobell_bean_burrito.png",[["bean burrito"], ["taco bell"]]],
  ["/foods/tacobell_chalupa_supreme.png",[["chalupa supreme"]]],
  ["/foods/tacobell_beefy_5layer_burrito.png",[["beefy 5-layer"]]],
  ["/foods/tacobell_doritos_locos_taco.png",[["doritos locos"]]],
  ["/foods/tacobell_cheese_quesadilla.png",[["cheese quesadilla"], ["taco bell"]]],
  ["/foods/tacobell_chicken_burrito.png",[["chicken burrito"], ["taco bell"]]],
  ["/foods/tacobell_nachos_cheese.png",[["nachos", "cheese"], ["taco bell"]]],
  ["/foods/wendys_daves_single.png",[["dave", "single"]]],
  ["/foods/wendys_daves_double.png",[["dave", "double"]]],
  ["/foods/wendys_daves_triple.png",[["dave", "triple"]]],
  ["/foods/wendys_baconator.png",[["baconator"]]],
  ["/foods/wendys_spicy_chicken_sandwich.png",[["spicy chicken sandwich"], ["wendy"]]],
  ["/foods/wendys_jr_cheeseburger.png",[["jr. cheeseburger"]]],
  ["/foods/wendys_jr_bacon_cheeseburger.png",[["jr. bacon cheeseburger"]]],
  ["/foods/wendys_nuggets_4ct.png",[["nuggets", "4"], ["wendy"]]],
  ["/foods/wendys_nuggets_10ct.png",[["nuggets", "10"], ["wendy"]]],
  ["/foods/wendys_large_fries.png",[["large fries"], ["wendy"]]],
  ["/foods/wendys_chili_small.png",[["chili", "small"], ["wendy"]]],
  ["/foods/wendys_chili_large.png",[["chili", "large"], ["wendy"]]],
  ["/foods/wendys_baked_potato.png",[["baked potato", "plain"], ["wendy"]]],
  ["/foods/wendys_frosty_chocolate.png",[["frosty", "chocolate"]]],
  ["/foods/wendys_frosty_vanilla.png",[["frosty", "vanilla"]]],
  ["/foods/wendys_classic_chicken_sandwich.png",[["classic chicken sandwich"], ["wendy"]]],
  ["/foods/bk_whopper.png",[["whopper"]]],
  ["/foods/bk_whopper_jr.png",[["whopper jr"]]],
  ["/foods/bk_whopper_with_cheese.png",[["whopper with cheese"]]],
  ["/foods/bk_original_chicken_sandwich.png",[["original chicken sandwich"], ["burger king"]]],
  ["/foods/bk_chicken_fries.png",[["chicken fries"]]],
  ["/foods/bk_onion_rings.png",[["onion rings"]]],
  ["/foods/bk_bacon_cheeseburger.png",[["bacon cheeseburger"], ["burger king"]]],
  ["/foods/bk_double_whopper.png",[["double whopper"]]],
  ["/foods/bk_impossible_whopper.png",[["impossible whopper"]]],
  ["/foods/bk_french_fries_medium.png",[["french fries", "medium"], ["burger king"]]],
  ["/foods/bk_chicken_jr.png",[["chicken jr"]]],
  ["/foods/bk_hash_browns.png",[["hash browns", "medium"], ["burger king"]]],
  ["/foods/fiveguys_cheeseburger.png",[["cheeseburger"], ["five guys"]]],
  ["/foods/fiveguys_little_cheeseburger.png",[["little cheeseburger"]]],
  ["/foods/fiveguys_bacon_cheeseburger.png",[["bacon cheeseburger"], ["five guys"]]],
  ["/foods/fiveguys_little_bacon_cheeseburger.png",[["little bacon cheeseburger"]]],
  ["/foods/fiveguys_cajun_fries.png",[["cajun fries"], ["five guys"]]],
  ["/foods/fiveguys_regular_fries.png",[["regular fries"], ["five guys"]]],
  ["/foods/fiveguys_hot_dog.png",[["hot dog"], ["five guys"]]],
  ["/foods/fiveguys_veggie_sandwich.png",[["veggie sandwich"], ["five guys"]]],
  ["/foods/panda_orange_chicken.png",[["orange chicken"]]],
  ["/foods/panda_beijing_beef.png",[["beijing beef"]]],
  ["/foods/panda_kung_pao_chicken.png",[["kung pao chicken"]]],
  ["/foods/panda_broccoli_beef.png",[["broccoli beef"]]],
  ["/foods/panda_fried_rice.png",[["fried rice"], ["panda"]]],
  ["/foods/panda_chow_mein.png",[["chow mein"]]],
  ["/foods/panda_super_greens.png",[["super greens"]]],
  ["/foods/panda_string_bean_chicken.png",[["string bean chicken"]]],
  ["/foods/panda_teriyaki_chicken.png",[["grilled teriyaki chicken"]]],
  ["/foods/panda_honey_walnut_shrimp.png",[["honey walnut shrimp"]]],
  ["/foods/panda_mushroom_chicken.png",[["mushroom chicken"]]],
  ["/foods/panda_steamed_white_rice.png",[["steamed white rice"], ["panda"]]],
  ["/foods/popeyes_classic_chicken_sandwich.png",[["classic chicken sandwich"], ["popeyes"]]],
  ["/foods/popeyes_spicy_chicken_sandwich.png",[["spicy chicken sandwich"], ["popeyes"]]],
  ["/foods/popeyes_chicken_breast.png",[["chicken breast", "mild"], ["popeyes"]]],
  ["/foods/popeyes_chicken_thigh.png",[["chicken thigh", "mild"], ["popeyes"]]],
  ["/foods/popeyes_cajun_fries.png",[["cajun fries"], ["popeyes"]]],
  ["/foods/popeyes_red_beans_rice.png",[["red beans", "rice"]]],
  ["/foods/popeyes_biscuit.png",[["biscuit"], ["popeyes"]]],
  ["/foods/popeyes_chicken_tenders.png",[["chicken tenders"], ["popeyes"]]],
  ["/foods/popeyes_mashed_potatoes.png",[["mashed potatoes", "gravy"]]],
  ["/foods/popeyes_coleslaw.png",[["coleslaw"]]],
  ["/foods/starbucks_caramel_frappuccino.png",[["caramel frappuccino"]]],
  ["/foods/starbucks_caffe_latte.png",[["caff\u00e3\u00a8 latte"], ["caffe latte"]]],
  ["/foods/starbucks_caffe_mocha.png",[["caff\u00e3\u00a8 mocha"], ["caffe mocha"]]],
  ["/foods/starbucks_pike_place_coffee.png",[["pike place"]]],
  ["/foods/starbucks_iced_caramel_macchiato.png",[["iced caramel macchiato"]]],
  ["/foods/starbucks_cake_pop.png",[["cake pop"]]],
  ["/foods/starbucks_bacon_gouda_sandwich.png",[["bacon gouda"]]],
  ["/foods/starbucks_spinach_feta_wrap.png",[["spinach feta"]]],
  ["/foods/starbucks_impossible_sandwich.png",[["impossible breakfast sandwich"]]],
  ["/foods/starbucks_butter_croissant.png",[["butter croissant"], ["starbucks"]]],
  ["/foods/starbucks_blueberry_muffin.png",[["blueberry muffin"], ["starbucks"]]],
  ["/foods/starbucks_banana_nut_bread.png",[["banana nut bread"]]],
  ["/foods/starbucks_protein_box.png",[["protein box", "eggs"]]],
  ["/foods/starbucks_vanilla_sweet_cream_cold_brew.png",[["vanilla sweet cream cold brew"]]],
  ["/foods/starbucks_matcha_latte.png",[["matcha latte"]]],
  ["/foods/starbucks_chai_tea_latte.png",[["chai tea latte"]]],
  ["/foods/starbucks_double_chocolate_brownie.png",[["double chocolate brownie"]]],
  ["/foods/dunkin_iced_coffee_cream_sugar.png",[["iced coffee", "cream", "sugar"], ["dunkin"]]],
  ["/foods/dunkin_iced_coffee_black.png",[["iced coffee", "black"], ["dunkin"]]],
  ["/foods/dunkin_glazed_donut.png",[["glazed donut"]]],
  ["/foods/dunkin_boston_kreme_donut.png",[["boston kreme"]]],
  ["/foods/dunkin_chocolate_frosted_donut.png",[["chocolate frosted donut"]]],
  ["/foods/dunkin_bacon_egg_cheese_croissant.png",[["bacon egg", "cheese croissant"]]],
  ["/foods/dunkin_bacon_egg_cheese_bagel.png",[["bacon egg", "cheese", "bagel"]]],
  ["/foods/dunkin_plain_bagel_cream_cheese.png",[["plain bagel with cream cheese"]]],
  ["/foods/dunkin_hash_browns.png",[["hash browns", "6"], ["dunkin"]]],
  ["/foods/dunkin_munchkins.png",[["munchkins"]]],
  ["/foods/dunkin_sausage_egg_cheese_wrap.png",[["wake-up wrap"]]],
  ["/foods/dunkin_hot_latte.png",[["hot latte"], ["dunkin"]]],
  ["/foods/pizzahut_cheese_pizza_slice.png",[["cheese pizza", "slice"], ["pizza hut"]]],
  ["/foods/pizzahut_pepperoni_pizza_slice.png",[["pepperoni pizza", "slice"], ["pizza hut"]]],
  ["/foods/pizzahut_supreme_pizza_slice.png",[["supreme pizza"], ["pizza hut"]]],
  ["/foods/pizzahut_breadsticks.png",[["breadstick"], ["pizza hut"]]],
  ["/foods/pizzahut_garlic_bread.png",[["garlic bread"], ["pizza hut"]]],
  ["/foods/pizzahut_bone_out_wings.png",[["bone-out wings"]]],
  ["/foods/dominos_cheese_pizza_slice.png",[["cheese", "slice"], ["domino"]]],
  ["/foods/dominos_pepperoni_pizza_slice.png",[["pepperoni", "slice"], ["domino"]]],
  ["/foods/dominos_cinnamon_bread_twists.png",[["cinnamon bread twists"]]],
  ["/foods/dominos_boneless_wings.png",[["boneless wings"], ["domino"]]],
  ["/foods/papajohns_cheese_pizza_slice.png",[["cheese", "slice"], ["papa john"]]],
  ["/foods/papajohns_pepperoni_pizza_slice.png",[["pepperoni", "slice"], ["papa john"]]],
  ["/foods/papajohns_garlic_knots.png",[["garlic knots"]]],
  ["/foods/papajohns_breadsticks.png",[["breadsticks"], ["papa john"]]],
  ["/foods/olivegarden_chicken_alfredo.png",[["chicken alfredo"], ["olive garden"]]],
  ["/foods/olivegarden_tour_of_italy.png",[["tour of italy"]]],
  ["/foods/olivegarden_breadstick.png",[["breadstick"], ["olive garden"]]],
  ["/foods/olivegarden_house_salad.png",[["house salad"], ["olive garden"]]],
  ["/foods/olivegarden_chicken_parmigiana.png",[["chicken parmigiana"]]],
  ["/foods/olivegarden_fettuccine_alfredo.png",[["fettuccine alfredo"]]],
  ["/foods/applebees_classic_burger.png",[["classic burger"], ["applebee"]]],
  ["/foods/applebees_boneless_wings.png",[["boneless wings"], ["applebee"]]],
  ["/foods/applebees_chicken_tenders_basket.png",[["chicken tenders basket"]]],
  ["/foods/applebees_loaded_fries.png",[["loaded fries"]]],
  ["/foods/chilis_oldtimer_burger.png",[["oldtimer"]]],
  ["/foods/chilis_chicken_crispers.png",[["chicken crispers"]]],
  ["/foods/chilis_baby_back_ribs.png",[["baby back ribs"]]],
  ["/foods/chilis_chicken_bacon_ranch_quesadillas.png",[["chicken bacon ranch quesadilla"]]],
  ["/foods/chilis_classic_buffalo_wings.png",[["classic buffalo wings"]]],
  ["/foods/tgifridays_cajun_shrimp_chicken_pasta.png",[["cajun shrimp", "chicken pasta"]]],
  ["/foods/tgifridays_fridays_burger.png",[["fridays burger"]]],
  ["/foods/tgifridays_sesame_jack_chicken_strips.png",[["sesame jack chicken strips"]]],
  ["/foods/quest_chocolate_chip_cookie_dough.png",[["chocolate chip cookie dough"], ["quest"]]],
  ["/foods/quest_birthday_cake.png",[["birthday cake"], ["quest"]]],
  ["/foods/rxbar_chocolate_sea_salt.png",[["chocolate sea salt"], ["rxbar"]]],
  ["/foods/rxbar_peanut_butter_chocolate.png",[["peanut butter chocolate"], ["rxbar"]]],
  ["/foods/onebar_birthday_cake.png",[["birthday cake"], ["one bar"]]],
  ["/foods/clifbar_crunchy_peanut_butter.png",[["crunchy peanut butter"], ["clif"]]],
  ["/foods/kind_dark_chocolate_nuts.png",[["dark chocolate nuts", "sea salt"]]],
  ["/foods/larabar_peanut_butter_chocolate_chip.png",[["peanut butter chocolate chip"], ["larabar"]]],
  ["/foods/cheerios.png",[["cheerios"]]],
  ["/foods/frosted_flakes.png",[["frosted flakes"]]],
  ["/foods/special_k.png",[["special k"]]],
  ["/foods/raisin_bran.png",[["raisin bran"]]],
  ["/foods/lucky_charms.png",[["lucky charms"]]],
  ["/foods/cinnamon_toast_crunch.png",[["cinnamon toast crunch"]]],
  ["/foods/honey_nut_cheerios.png",[["honey nut cheerios"]]],
  ["/foods/froot_loops.png",[["froot loops"]]],
  ["/foods/doritos_nacho_cheese.png",[["nacho cheese doritos"]]],
  ["/foods/doritos_cool_ranch.png",[["cool ranch doritos"]]],
  ["/foods/cheez_its_original.png",[["cheez-it"]]],
  ["/foods/goldfish_cheddar.png",[["goldfish"]]],
  ["/foods/hard_pretzels.png",[["hard pretzels"]]],
  ["/foods/rice_cakes_lightly_salted.png",[["rice cakes"]]],
  ["/foods/movie_theater_popcorn.png",[["movie theater popcorn"]]],
  ["/foods/skinny_pop.png",[["skinny pop"]]],
  ["/foods/trail_mix.png",[["trail mix"]]],
  ["/foods/beef_jerky_original.png",[["original beef jerky"]]],
  ["/foods/beef_jerky_teriyaki.png",[["teriyaki beef jerky"]]],
  ["/foods/cheddar_sour_cream_chips.png",[["cheddar", "sour cream", "chips"]]],
  ["/foods/peanut_butter_crackers.png",[["peanut butter crackers"]]],
  ["/foods/veggie_straws_original.png",[["veggie straws"]]],
  ["/foods/lean_cuisine_chicken_alfredo.png",[["chicken alfredo"], ["lean cuisine"]]],
  ["/foods/lean_cuisine_herb_roasted_chicken.png",[["herb roasted chicken"]]],
  ["/foods/healthy_choice_cafe_steamers.png",[["caf\u00e3\u00a9 steamers"], ["cafe steamers"]]],
  ["/foods/healthy_choice_power_bowl.png",[["power bowl"]]],
  ["/foods/hot_pockets_cheese_pizza.png",[["cheese pizza pocket"]]],
  ["/foods/hot_pockets_pepperoni_pizza.png",[["pepperoni pizza pocket"]]],
  ["/foods/digiorno_cheese_pizza_slice.png",[["digiorno", "cheese"]]],
  ["/foods/digiorno_pepperoni_pizza_slice.png",[["digiorno", "pepperoni"]]],
  ["/foods/totinos_pizza_rolls.png",[["pizza rolls"]]],
  ["/foods/totinos_party_pizza.png",[["party pizza"]]],
  ["/foods/amys_bean_cheese_burrito.png",[["burrito", "bean", "cheese"], ["amy"]]],
  ["/foods/amys_cheese_enchilada.png",[["cheese enchilada"]]],
  ["/foods/daves_killer_bread_21_grains.png",[["21 whole grains"]]],
  ["/foods/daves_killer_bread_good_seed.png",[["good seed"]]],
  ["/foods/ezekiel_sprouted_bread.png",[["ezekiel"]]],
  ["/foods/english_muffin_whole_wheat.png",[["english muffin"]]],
  ["/foods/pita_bread.png",[["pita bread"]]],
  ["/foods/naan_bread.png",[["naan"]]],
  ["/foods/croissant_large.png",[["croissant", "large"]]],
  ["/foods/hamburger_bun.png",[["hamburger bun"]]],
  ["/foods/fairlife_2percent_milk.png",[["fairlife 2"]]],
  ["/foods/fairlife_fat_free_milk.png",[["fairlife fat free"]]],
  ["/foods/chobani_vanilla_greek_yogurt.png",[["vanilla greek yogurt", "chobani"]]],
  ["/foods/yoplait_strawberry_yogurt.png",[["strawberry yogurt", "yoplait"]]],
  ["/foods/light_string_cheese.png",[["string cheese"]]],
  ["/foods/cottage_cheese_4percent.png",[["cottage cheese", "4"]]],
  ["/foods/parmesan_cheese_grated.png",[["parmesan"]]],
  ["/foods/swiss_cheese_slice.png",[["swiss cheese"]]],
  ["/foods/vanilla_ice_cream.png",[["vanilla ice cream"]]],
  ["/foods/chocolate_ice_cream.png",[["chocolate ice cream"]]],
  ["/foods/frozen_yogurt_vanilla.png",[["frozen yogurt", "vanilla"]]],
  ["/foods/brownie_homemade.png",[["brownie", "homemade"]]],
  ["/foods/chocolate_chip_cookie_large.png",[["chocolate chip cookie", "large"]]],
  ["/foods/cheesecake_slice.png",[["cheesecake", "slice"]]],
  ["/foods/apple_pie_slice.png",[["apple pie", "slice"]]],
  ["/foods/plain_glazed_donut.png",[["plain glazed donut"]]],
  ["/foods/cinnamon_roll_large.png",[["cinnamon roll", "large"]]],
  ["/foods/blueberry_muffin_bakery.png",[["blueberry muffin", "bakery"]]],
  ["/foods/pancakes_3.png",[["pancakes", "plain", "3"]]],
  ["/foods/waffles_2.png",[["waffles", "plain", "2"]]],
  ["/foods/french_toast_2_slices.png",[["french toast", "2 slices"]]],
  ["/foods/dark_chocolate_70.png",[["dark chocolate", "70"]]],
  ["/foods/milk_chocolate.png",[["milk chocolate"]]],
  ["/foods/snickers_bar.png",[["snickers bar"]]],
  ["/foods/kit_kat_4finger.png",[["kit kat"]]],
  ["/foods/reeses_peanut_butter_cups.png",[["reese", "s peanut butter cups"]]],
  ["/foods/mms_peanut.png",[["m&m", "peanut"]]],
  ["/foods/skittles_original.png",[["skittles", "original"]]],
  ["/foods/oreo_cookies_3.png",[["oreo", "3"]]],
  ["/foods/chips_ahoy_3.png",[["chips ahoy"]]],
  ["/foods/rice_krispies_treat.png",[["rice krispies treat"]]],
  ["/foods/pop_tart_frosted_strawberry.png",[["pop-tart", "strawberry"]]],
  ["/foods/ben_and_jerrys_chocolate_fudge_brownie.png",[["ben", "jerry", "chocolate fudge brownie"]]],
  ["/foods/halo_top_vanilla_bean.png",[["halo top", "vanilla bean"]]],
  ["/foods/arroz_blanco.png",[["arroz blanco"]]],
  ["/foods/arroz_amarillo.png",[["arroz amarillo"]]],
  ["/foods/arroz_con_gandules.png",[["arroz con gandules"]]],
  ["/foods/arroz_con_pollo.png",[["arroz con pollo"]]],
  ["/foods/arroz_con_habichuelas.png",[["arroz con habichuelas"]]],
  ["/foods/arroz_con_salchichas.png",[["arroz con salchichas"]]],
  ["/foods/arroz_con_maiz.png",[["arroz con ma\u00e3\u00adz"], ["arroz con maiz"]]],
  ["/foods/arroz_mamposteao.png",[["mamposteao"]]],
  ["/foods/arroz_con_dulce.png",[["arroz con dulce"]]],
  ["/foods/pegao.png",[["pegao"]]],
  ["/foods/habichuelas_guisadas_rosadas.png",[["habichuelas guisadas", "rosadas"]]],
  ["/foods/habichuelas_guisadas_rojas.png",[["habichuelas guisadas", "rojas"]]],
  ["/foods/habichuelas_guisadas_blancas.png",[["habichuelas guisadas", "blancas"]]],
  ["/foods/habichuelas_negras_guisadas.png",[["habichuelas negras"]]],
  ["/foods/gandules_guisados.png",[["gandules guisados"]]],
  ["/foods/pernil.png",[["pernil"]]],
  ["/foods/lechon_asado.png",[["lech\u00e3\u00b3n asado"], ["lechon asado"]]],
  ["/foods/pollo_guisado.png",[["pollo guisado"]]],
  ["/foods/carne_guisada.png",[["carne guisada"]]],
  ["/foods/bistec_encebollado.png",[["bistec encebollado"]]],
  ["/foods/chuleta_kan_kan.png",[["chuleta kan kan"]]],
  ["/foods/churrasco.png",[["churrasco"]]],
  ["/foods/pollo_frito.png",[["pollo frito"]]],
  ["/foods/pollo_a_la_brasa.png",[["pollo a la brasa"]]],
  ["/foods/carne_frita.png",[["carne frita"]]],
  ["/foods/chicharron_de_pollo.png",[["chicharr\u00e3\u00b3n de pollo"], ["chicharron de pollo"]]],
  ["/foods/chicharron_de_cerdo.png",[["chicharr\u00e3\u00b3n de cerdo"], ["chicharron de cerdo"]]],
  ["/foods/camarones_al_ajillo.png",[["camarones al ajillo"]]],
  ["/foods/mofongo_relleno_camarones.png",[["mofongo", "camarones"]]],
  ["/foods/asopao_de_camarones.png",[["asopao de camarones"]]],
  ["/foods/pescado_frito.png",[["pescado frito"]]],
  ["/foods/ensalada_de_pulpo.png",[["ensalada de pulpo"]]],
  ["/foods/bacalao_guisado.png",[["bacalao guisado"]]],
  ["/foods/serenata_de_bacalao.png",[["serenata de bacalao"]]],
  ["/foods/mofongo_plain.png",[["mofongo"]]],
  ["/foods/mofongo_relleno_pollo.png",[["mofongo", "pollo"]]],
  ["/foods/mofongo_relleno_carne.png",[["mofongo", "carne"]]],
  ["/foods/tostones.png",[["tostones"]]],
  ["/foods/amarillos_maduros.png",[["amarillos"], ["maduros"]]],
  ["/foods/trifongo.png",[["trifongo"]]],
  ["/foods/mofongo_de_yuca.png",[["mofongo de yuca"]]],
  ["/foods/alcapurria_meat.png",[["alcapurria", "meat"], ["alcapurria", "carne"]]],
  ["/foods/alcapurria_crab.png",[["alcapurria", "crab"], ["alcapurria", "jueyes"]]],
  ["/foods/bacalaito.png",[["bacala\u00e3\u00adto"], ["bacalaito"]]],
  ["/foods/empanadilla_carne.png",[["empanadilla de carne"]]],
  ["/foods/empanadilla_pollo.png",[["empanadilla de pollo"]]],
  ["/foods/empanadilla_pizza.png",[["empanadilla de pizza"]]],
  ["/foods/sorullito_de_maiz.png",[["sorullito"]]],
  ["/foods/relleno_de_papa.png",[["relleno de papa"]]],
  ["/foods/papa_rellena.png",[["papa rellena"]]],
  ["/foods/pionono.png",[["pionono"]]],
  ["/foods/aranitas_de_platano.png",[["ara\u00e3\u00b1itas"], ["aranitas"]]],
  ["/foods/toston_relleno.png",[["tost\u00e3\u00b3n relleno"], ["toston relleno"]]],
  ["/foods/sancocho_puertorriqueno.png",[["sancocho puertorrique\u00e3\u00b1o"], ["sancocho puertorriqueno"]]],
  ["/foods/asopao_de_pollo.png",[["asopao de pollo"]]],
  ["/foods/sopa_de_pollo_fideos.png",[["sopa de pollo con fideos"]]],
  ["/foods/sopa_de_platano.png",[["sopa de pl\u00e3\u00a1tano"], ["sopa de platano"]]],
  ["/foods/caldo_de_res.png",[["caldo de res"]]],
  ["/foods/yuca_hervida.png",[["yuca hervida"]]],
  ["/foods/yuca_frita.png",[["yuca frita"]]],
  ["/foods/batata_boniato.png",[["batata"], ["boniato"]]],
  ["/foods/guineo_verde_hervido.png",[["guineo verde"]]],
  ["/foods/platano_hervido.png",[["pl\u00e3\u00a1tano hervido"], ["platano hervido"]]],
  ["/foods/ensalada_de_coditos.png",[["ensalada de coditos"]]],
  ["/foods/ensalada_de_papa.png",[["ensalada de papa"]]],
  ["/foods/pastelon_de_platano_maduro.png",[["pastel\u00e3\u00b3n"], ["pastelon"]]],
  ["/foods/pasteles_pork.png",[["pasteles", "pork"], ["pasteles", "cerdo"]]],
  ["/foods/pasteles_de_yuca.png",[["pasteles de yuca"]]],
  ["/foods/lasagna_boricua.png",[["lasagna boricua"]]],
  ["/foods/huevos_revueltos_jamon.png",[["huevos revueltos"]]],
  ["/foods/tortilla_de_huevo.png",[["tortilla de huevo"]]],
  ["/foods/avena_pr.png",[["avena"]]],
  ["/foods/pan_sobao.png",[["pan sobao"]]],
  ["/foods/pan_de_agua.png",[["pan de agua"]]],
  ["/foods/mallorca_bread.png",[["mallorca"]]],
  ["/foods/mallorca_jamon_queso.png",[["mallorca", "jam\u00e3\u00b3n"], ["mallorca", "jamon"]]],
  ["/foods/quesito.png",[["quesito"]]],
  ["/foods/pastelillo_de_guayaba.png",[["pastelillo de guayaba"]]],
  ["/foods/pastelillo_guayaba_queso.png",[["pastelillo", "guayaba", "queso"]]],
  ["/foods/tembleque.png",[["tembleque"]]],
  ["/foods/flan_de_queso.png",[["flan de queso"]]],
  ["/foods/flan_de_coco.png",[["flan de coco"]]],
  ["/foods/tres_leches_cake.png",[["tres leches"]]],
  ["/foods/limber_de_coco.png",[["limber de coco"]]],
  ["/foods/piragua.png",[["piragua"]]],
  ["/foods/cafe_con_leche.png",[["caf\u00e3\u00a9 con leche"], ["cafe con leche"]]],
  ["/foods/cafe_puya.png",[["caf\u00e3\u00a9 puya"], ["cafe puya"]]],
  ["/foods/malta_india.png",[["malta india"]]],
  ["/foods/coquito.png",[["coquito"]]],
  ["/foods/jugo_de_parcha.png",[["jugo de parcha"]]],
  ["/foods/jugo_de_guayaba.png",[["jugo de guayaba"]]],
  ["/foods/pina_colada.png",[["pi\u00e3\u00b1a colada"], ["pina colada"]]],
  ["/foods/polloTropical_tropichop.png",[["tropichop"]]],
  ["/foods/polloTropical_quarter_chicken_dark.png",[["quarter chicken", "dark"], ["pollo tropical"]]],
  ["/foods/polloTropical_quarter_chicken_white.png",[["quarter chicken", "white"], ["pollo tropical"]]],
  ["/foods/polloTropical_moro_rice.png",[["moro rice"]]],
  ["/foods/polloTropical_sweet_plantains.png",[["sweet plantains"], ["pollo tropical"]]],
  ["/foods/pica_pollo.png",[["pica pollo"]]],
  ["/foods/yaroa_de_pollo.png",[["yaroa"]]],
  ["/foods/mangu.png",[["mang\u00e3\u00ba"], ["mangu"]]],
  ["/foods/tres_golpes.png",[["tres golpes"]]],
  ["/foods/sancocho_dominicano.png",[["sancocho dominicano"]]],
  ["/foods/chimichurri_burger.png",[["chimichurri burger"]]],
  ["/foods/moro_habichuelas_negras.png",[["moro de habichuelas negras"]]],
  ["/foods/moro_gandules.png",[["moro de gandules"]]],
  ["/foods/habichuela_con_dulce.png",[["habichuela con dulce"]]],
  ["/foods/concon.png",[["conc\u00e3\u00b3n"], ["concon"]]],
  ["/foods/chofan.png",[["chof\u00e3\u00a1n"], ["chofan"]]],
  ["/foods/cubano_sandwich.png",[["cubano sandwich"]]],
  ["/foods/ropa_vieja.png",[["ropa vieja"]]],
  ["/foods/vaca_frita.png",[["vaca frita"]]],
  ["/foods/medianoche_sandwich.png",[["medianoche"]]],
  ["/foods/croquetas_de_jamon.png",[["croquetas de jam\u00e3\u00b3n"], ["croquetas de jamon"]]],
  ["/foods/california_roll.png",[["california roll"]]],
  ["/foods/spicy_tuna_roll.png",[["spicy tuna roll"]]],
  ["/foods/salmon_roll.png",[["salmon roll"]]],
  ["/foods/pad_thai_chicken.png",[["pad thai", "chicken"]]],
  ["/foods/fried_rice_takeout.png",[["fried rice", "takeout"]]],
  ["/foods/lo_mein_chicken.png",[["lo mein", "chicken"]]],
  ["/foods/general_tsos_chicken.png",[["general tso"]]],
  ["/foods/chicken_tikka_masala.png",[["chicken tikka masala"]]],
  ["/foods/falafel.png",[["falafel"]]],
  ["/foods/chicken_shawarma_wrap.png",[["chicken shawarma"]]],
  ["/foods/gyro_lamb_beef.png",[["gyro"]]],
  ["/foods/pho_beef.png",[["pho"]]],
  ["/foods/instant_ramen.png",[["instant ramen"]]],
  ["/foods/restaurant_ramen_tonkotsu.png",[["ramen", "tonkotsu"]]],
  ["/foods/bibimbap.png",[["bibimbap"]]],
  ["/foods/pork_tamale.png",[["pork tamale"]]],
  ["/foods/beef_empanada.png",[["beef empanada"]]],
  ["/foods/pupusa_cheese.png",[["pupusa"]]],
  ["/foods/jerk_chicken_thigh.png",[["jerk chicken"]]],
  ["/foods/chicken_curry_thai_green.png",[["thai green", "curry"], ["chicken curry", "thai"]]],
  ["/foods/chicken_curry_japanese.png",[["japanese", "curry"], ["chicken curry", "japanese"]]],
  ["/foods/pork_dumplings_steamed.png",[["pork dumplings", "steamed"]]],
  ["/foods/pork_dumplings_fried.png",[["pork dumplings", "fried"]]],
  ["/foods/vegetable_spring_rolls.png",[["vegetable spring rolls"]]],
  ["/foods/pork_egg_rolls.png",[["pork egg rolls"]]],
  ["/foods/arepas_cheese.png",[["arepas", "cheese"]]],
  ["/foods/chicken_teriyaki_bowl.png",[["chicken teriyaki bowl"]]],
  ["/foods/butter_chicken.png",[["butter chicken"]]],
  ["/foods/lamb_curry_vindaloo.png",[["lamb", "vindaloo"]]],
  ["/foods/vegetable_samosa.png",[["vegetable samosa"]]],
  ["/foods/chicken_satay.png",[["chicken satay"]]],
  ["/foods/innout_double_double.png",[["double-double"]]],
  ["/foods/innout_cheeseburger_protein_style.png",[["protein style"], ["in-n-out"]]],
  ["/foods/innout_animal_style_fries.png",[["animal style fries"]]],
  ["/foods/deltaco_crunchy_taco.png",[["crunchy taco"], ["del taco"]]],
  ["/foods/whitecastle_original_slider.png",[["original slider"], ["white castle"]]],
  ["/foods/mcdonalds_6pc_nuggets_meal.png",[["6pc", "mcnuggets", "meal"], ["6 piece", "mcnuggets", "medium", "meal"]]],
  ["/foods/mcdonalds_bacon_clubhouse_burger.png",[["bacon clubhouse"]]],
  ["/foods/mcdonalds_grilled_chicken_deluxe.png",[["grilled chicken deluxe"]]],
  ["/foods/qdoba_chicken_burrito_bowl.png",[["chicken burrito bowl"], ["qdoba"]]],
  ["/foods/arbys_original_roast_beef.png",[["original roast beef"], ["arby"]]],
  // Fallback mappings for items without dedicated images
  ["/foods/whey_protein_shake.png",[["creatine monohydrate"], ["bcaa powder"]]],
  ["/foods/olive_oil.png",[["cooking spray"], ["pam"]]],
  ["/foods/asopao_de_pollo.png",[["sopa de salchich"]]],
  ["/foods/tembleque.png",[["majarete"]]],
  ["/foods/pancakes_3.png",[["panqueques con sirope"]]],
  ["/foods/tres_leches_cake.png",[["bizcocho de ron"]]],
  ["/foods/quesito.png",[["mantecaditos"], ["polvor"]]],
  ["/foods/limber_de_coco.png",[["limber de parcha"]]],
  ["/foods/tembleque.png",[["dulce de lechoza"], ["besitos de coco"]]],
  ["/foods/arroz_con_dulce.png",[["arroz con coco"]]],
  ["/foods/jugo_de_guayaba.png",[["jugo de acerola"]]],
  ["/foods/pina_colada.png",[["morir so"]]],
  ["/foods/malta_india.png",[["medalla light"]]],
  ["/foods/empanadilla_pollo.png",[["pastelitos dominicanos"]]],
  ["/foods/beef_empanada.png",[["empanada de carne"]]],
  ["/foods/arepas_cheese.png",[["arepas de queso"]]],
];

const cache = new Map();

export function getFoodImage(name, brand) {
  if (!name) return null;
  const key = brand ? `${name}||${brand}` : name;
  const c = cache.get(key);
  if (c !== undefined) return c;
  // Search against combined "brand name" so branded items match patterns like "chick-fil-a" + "nuggets"
  const l = brand ? `${brand} ${name}`.toLowerCase() : name.toLowerCase();
  for (const [img, pats] of R) {
    for (const parts of pats) {
      if (parts.every(p => l.includes(p))) { cache.set(key, img); return img; }
    }
  }
  // Fallback: try name-only match (for non-branded items)
  if (brand) {
    const nameOnly = name.toLowerCase();
    for (const [img, pats] of R) {
      for (const parts of pats) {
        if (parts.every(p => nameOnly.includes(p))) { cache.set(key, img); return img; }
      }
    }
  }
  cache.set(key, null);
  return null;
}
