// swUpdate.js
// -----------------------------------------------------------------------------
// Service-worker update signal for the WEB app.
//
// vite.config.js ships the SW as `registerType: 'prompt'`, which means a new
// build installs and then WAITS instead of seizing the tab you already have
// open. That is the whole point — see the long note in vite.config.js — but it
// leaves one job here: telling the user an update is ready, and applying it
// when they say so.
//
// Without this file a long-lived tab (or an installed PWA that never really
// closes) would sit on an old build indefinitely. With it, the update is
// deliberate: the page reloads when the user chooses, not underneath them.
//
// NOT the same thing as appVersionCheck.js. That one is a hard server-driven
// gate — "this build is too old to talk to the API, you must update". This is
// the soft, routine "there's a newer build sitting ready".
// -----------------------------------------------------------------------------

import { Capacitor } from '@capacitor/core';

const listeners = new Set();
let needsRefresh = false;
let updateSW = null;

/** Subscribe to "an update is waiting". Fires immediately if one already is. */
export function subscribeSWUpdate(fn) {
  listeners.add(fn);
  if (needsRefresh) fn(true);
  return () => listeners.delete(fn);
}

/** Activate the waiting service worker and reload onto the new build. */
export function applySWUpdate() {
  // updateSW(true) tells the waiting SW to skipWaiting, then reloads once it
  // has taken control. Reloading ourselves instead would race it and could
  // land back on the old build.
  if (typeof updateSW === 'function') updateSW(true);
  else if (typeof window !== 'undefined') window.location.reload();
}

export async function initSWUpdate() {
  // Native ships `selfDestroying: isCapacitor` — there is no SW to update, and
  // the bundle comes from the native assets / Capgo instead.
  if (Capacitor.isNativePlatform()) return;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;

  try {
    // Dynamic import: `virtual:pwa-register` is generated by vite-plugin-pwa.
    // Importing it lazily keeps it out of the entry chunk and means a resolution
    // problem degrades to "no update banner" instead of breaking boot.
    const { registerSW } = await import('virtual:pwa-register');
    updateSW = registerSW({
      immediate: true,
      onNeedRefresh() {
        needsRefresh = true;
        listeners.forEach((fn) => { try { fn(true); } catch { /* one bad listener */ } });
      },
    });
  } catch {
    /* No SW tooling available — the app just never offers an update. */
  }
}
