// Regenerates src/data/exerciseMeta.js — a lightweight id→name/videoUrl map
// for screens (Dashboard) that only need names + videos, not the full 104KB
// exercise library. Run: node scripts/genExerciseMeta.mjs
import { exercises } from '../src/data/exercises.js';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const meta = exercises.map(e => ({ id: e.id, name: e.name, ...(e.videoUrl ? { videoUrl: e.videoUrl } : {}) }));
const body = `// AUTO-GENERATED by scripts/genExerciseMeta.mjs — do not edit by hand.
// Lightweight id→name/videoUrl map so Dashboard (eager-loaded) doesn't pull the
// full ~104KB exercise library (instructions, muscleScores, regions) into the
// critical entry chunk. Regenerate if exercise names/videos change.
export const exerciseMeta = ${JSON.stringify(meta)};
`;
writeFileSync(resolve(__dirname, '../src/data/exerciseMeta.js'), body);
console.log('wrote', meta.length, 'entries,', body.length, 'bytes (source exercises.js is ~104KB)');
