-- =============================================================
-- SEED: EXERCISE LIBRARY
-- Migration: 0003_seed_exercises.sql
-- Run AFTER 0001 and 0002.
-- =============================================================
-- Migrates all exercises from src/data/exercises.js into the
-- exercises table. gym_id IS NULL = global (visible to all gyms).
-- IDs are preserved exactly ('ex_bp', 'ex_sq', etc.) so all
-- existing frontend references continue to work without changes.
-- =============================================================

INSERT INTO exercises (id, name, muscle_group, equipment, category, default_sets, default_reps, rest_seconds, instructions, primary_regions, secondary_regions)
VALUES

-- ── CHEST ──────────────────────────────────────────────────
('ex_bp',
 'Barbell Bench Press',
 'Chest', 'Barbell', 'Strength',
 4, '5', 120,
 'Lie flat, grip just outside shoulder width, lower bar to mid-chest, press up.',
 ARRAY['mid_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_ibp',
 'Incline Barbell Press',
 'Chest', 'Barbell', 'Hypertrophy',
 3, '8-10', 90,
 'Set bench to 30-45°. Grip slightly narrower. Lower bar to upper chest.',
 ARRAY['upper_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_dbp',
 'Dumbbell Bench Press',
 'Chest', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Neutral or pronated grip. Lower dumbbells to chest level with elbows at 75°.',
 ARRAY['mid_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_idbp',
 'Incline Dumbbell Press',
 'Chest', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Incline 30-45°. Same motion as flat dumbbell press, targeting upper chest.',
 ARRAY['upper_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_cfly',
 'Cable Fly',
 'Chest', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Set cables at shoulder height. Bring handles together in a hugging motion.',
 ARRAY['mid_chest'],
 ARRAY['front_delts', 'biceps']),

('ex_dfly',
 'Dumbbell Fly',
 'Chest', 'Dumbbell', 'Hypertrophy',
 3, '12-15', 60,
 'Flat bench. Wide arc, slight elbow bend. Squeeze chest at top.',
 ARRAY['mid_chest', 'upper_chest'],
 ARRAY['front_delts']),

('ex_dips',
 'Weighted Dips',
 'Chest', 'Bodyweight', 'Strength',
 3, '8-12', 90,
 'Lean slightly forward to bias chest. Full ROM, lock out at top.',
 ARRAY['mid_chest', 'triceps'],
 ARRAY['front_delts']),

-- ── BACK ───────────────────────────────────────────────────
('ex_dl',
 'Conventional Deadlift',
 'Back', 'Barbell', 'Strength',
 4, '3-5', 180,
 'Hip-width stance. Hinge, grip outside knees. Drive hips forward to lockout.',
 ARRAY['lower_back', 'hamstrings', 'glutes'],
 ARRAY['upper_back', 'lats', 'forearms']),

('ex_bbr',
 'Barbell Row',
 'Back', 'Barbell', 'Strength',
 4, '6-8', 120,
 'Hinge to ~45°. Pull bar to lower chest/navel. Keep elbows close.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps', 'lower_back']),

('ex_pu',
 'Pull-Up',
 'Back', 'Bodyweight', 'Strength',
 4, '6-12', 120,
 'Shoulder-width overhand grip. Pull chest to bar, full hang at bottom.',
 ARRAY['lats'],
 ARRAY['biceps', 'upper_back', 'forearms']),

('ex_lp',
 'Lat Pulldown',
 'Back', 'Cable', 'Hypertrophy',
 3, '10-12', 90,
 'Wide overhand grip. Pull bar to upper chest, elbows drive down.',
 ARRAY['lats'],
 ARRAY['biceps', 'upper_back']),

('ex_cbr',
 'Cable Row',
 'Back', 'Cable', 'Hypertrophy',
 3, '10-12', 90,
 'Sit upright. Pull handle to abdomen, squeeze shoulder blades.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps']),

('ex_dbr',
 'Dumbbell Row',
 'Back', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Knee and hand on bench. Pull dumbbell to hip, elbow close to body.',
 ARRAY['lats', 'upper_back'],
 ARRAY['biceps', 'rear_delts']),

('ex_rdl',
 'Romanian Deadlift',
 'Back', 'Barbell', 'Hypertrophy',
 3, '8-10', 90,
 'Slight knee bend. Hinge at hips, bar slides down legs. Feel hamstring stretch.',
 ARRAY['hamstrings', 'glutes'],
 ARRAY['lower_back', 'forearms']),

-- ── SHOULDERS ──────────────────────────────────────────────
('ex_ohp',
 'Overhead Press',
 'Shoulders', 'Barbell', 'Strength',
 4, '5', 120,
 'Shoulder-width grip. Bar from clavicle, press overhead, lock out.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['triceps', 'traps']),

('ex_dbop',
 'Dumbbell Shoulder Press',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Seated or standing. Press dumbbells overhead from shoulder height.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['triceps']),

('ex_lr',
 'Lateral Raise',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '15-20', 60,
 'Slight elbow bend. Raise to shoulder height. Lead with elbows.',
 ARRAY['side_delts'],
 ARRAY['traps']),

('ex_fr',
 'Front Raise',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '12-15', 60,
 'Alternate arms. Raise to eye level with slight elbow bend.',
 ARRAY['front_delts'],
 ARRAY['side_delts']),

('ex_rfly',
 'Rear Delt Fly',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '15-20', 60,
 'Hinge to 45°. Raise dumbbells to sides, lead with elbows.',
 ARRAY['rear_delts'],
 ARRAY['traps', 'upper_back']),

('ex_fcu',
 'Face Pull',
 'Shoulders', 'Cable', 'Hypertrophy',
 3, '15-20', 60,
 'Cable at eye height. Pull to face with elbows flared, external rotate.',
 ARRAY['rear_delts'],
 ARRAY['traps', 'side_delts']),

-- ── BICEPS ─────────────────────────────────────────────────
('ex_bbc',
 'Barbell Curl',
 'Biceps', 'Barbell', 'Hypertrophy',
 3, '8-12', 60,
 'Shoulder-width underhand grip. Full ROM. No swinging.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_dbc',
 'Dumbbell Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Alternate or together. Supinate at the top. Full ROM.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_hc',
 'Hammer Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Neutral grip throughout. Targets brachialis and brachioradialis.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_cc',
 'Cable Curl',
 'Biceps', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Constant tension. Use straight or EZ-bar attachment.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_pcc',
 'Preacher Curl',
 'Biceps', 'Machine', 'Hypertrophy',
 3, '10-12', 60,
 'Isolates the bicep. Full stretch at bottom. Slow eccentric.',
 ARRAY['biceps'],
 ARRAY[]::TEXT[]),

-- ── TRICEPS ────────────────────────────────────────────────
('ex_tpd',
 'Tricep Pushdown',
 'Triceps', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Rope or bar attachment. Keep elbows at sides. Full extension.',
 ARRAY['triceps'],
 ARRAY[]::TEXT[]),

('ex_ske',
 'Skull Crusher',
 'Triceps', 'Barbell', 'Hypertrophy',
 3, '10-12', 60,
 'Flat bench. Lower bar to forehead, extend to lockout.',
 ARRAY['triceps'],
 ARRAY[]::TEXT[]),

('ex_oe',
 'Overhead Tricep Extension',
 'Triceps', 'Dumbbell', 'Hypertrophy',
 3, '12-15', 60,
 'Both hands on one dumbbell. Lower behind head, extend fully.',
 ARRAY['triceps'],
 ARRAY[]::TEXT[]),

('ex_cgp',
 'Close-Grip Bench Press',
 'Triceps', 'Barbell', 'Strength',
 3, '8-10', 90,
 'Hands 12-16 inches apart. Elbows tucked, lower to lower chest.',
 ARRAY['triceps', 'mid_chest'],
 ARRAY['front_delts']),

-- ── LEGS ───────────────────────────────────────────────────
('ex_sq',
 'Barbell Back Squat',
 'Legs', 'Barbell', 'Strength',
 4, '5', 180,
 'High or low bar. Shoulder-width stance. Squat to parallel or below.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors', 'lower_back']),

('ex_fsq',
 'Front Squat',
 'Legs', 'Barbell', 'Strength',
 3, '5-6', 180,
 'Bar on front delts. Stay upright. Knees track over toes.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors']),

('ex_lp_l',
 'Leg Press',
 'Legs', 'Machine', 'Hypertrophy',
 4, '10-15', 90,
 'Feet shoulder-width. Lower until 90° at knee. Full extension.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors', 'hamstrings']),

('ex_le',
 'Leg Extension',
 'Legs', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Isolates quads. Full extension, slow eccentric.',
 ARRAY['quads'],
 ARRAY[]::TEXT[]),

('ex_lc',
 'Leg Curl',
 'Legs', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Lying or seated. Full ROM. Squeeze hamstrings at peak contraction.',
 ARRAY['hamstrings'],
 ARRAY['glutes']),

('ex_lunge',
 'Walking Lunge',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '12 each', 60,
 'Step forward, lower back knee to just above ground. Keep torso upright.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors', 'hamstrings']),

('ex_bdl',
 'Bulgarian Split Squat',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '10-12 each', 90,
 'Rear foot elevated. Lower until front thigh is parallel. Control descent.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors', 'hamstrings']),

-- ── GLUTES ─────────────────────────────────────────────────
('ex_hth',
 'Hip Thrust',
 'Glutes', 'Barbell', 'Strength',
 4, '8-12', 90,
 'Upper back on bench, bar on hip. Drive hips up, squeeze glutes at top.',
 ARRAY['glutes'],
 ARRAY['hamstrings']),

('ex_kg',
 'Kettlebell Swing',
 'Glutes', 'Kettlebell', 'Power',
 4, '15-20', 60,
 'Hip hinge, drive hips forward explosively. Bell floats to chest height.',
 ARRAY['glutes', 'hamstrings'],
 ARRAY['lower_back', 'adductors']),

-- ── CORE ───────────────────────────────────────────────────
('ex_plank',
 'Plank',
 'Core', 'Bodyweight', 'Endurance',
 3, '60s', 60,
 'Forearms on ground. Rigid straight body. Squeeze glutes and abs.',
 ARRAY['abs'],
 ARRAY['obliques', 'glutes']),

('ex_cr',
 'Cable Crunch',
 'Core', 'Cable', 'Hypertrophy',
 3, '15-20', 60,
 'Kneel, rope behind head. Crunch down pulling elbows to knees.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_llr',
 'Hanging Leg Raise',
 'Core', 'Bodyweight', 'Strength',
 3, '12-15', 60,
 'Dead hang, raise legs to 90° or higher. Control descent.',
 ARRAY['abs'],
 ARRAY['obliques', 'forearms']),

('ex_abwh',
 'Ab Wheel Rollout',
 'Core', 'Bodyweight', 'Strength',
 3, '8-12', 60,
 'Kneel, roll forward keeping back flat. Pull back with abs, not hips.',
 ARRAY['abs'],
 ARRAY['obliques', 'lower_back']),

-- ── CALVES ─────────────────────────────────────────────────
('ex_scr',
 'Standing Calf Raise',
 'Calves', 'Machine', 'Hypertrophy',
 4, '15-20', 45,
 'Full ROM. Pause at bottom stretch. Squeeze at top.',
 ARRAY['calves'],
 ARRAY[]::TEXT[]),

('ex_secr',
 'Seated Calf Raise',
 'Calves', 'Machine', 'Hypertrophy',
 4, '15-20', 45,
 'Targets soleus. Same full ROM emphasis.',
 ARRAY['calves'],
 ARRAY[]::TEXT[]);
