-- =============================================================
-- EXPAND EXERCISE LIBRARY
-- Migration: 0045_expand_exercise_library.sql
-- =============================================================
-- Inserts ~100+ new exercises covering machines, bodyweight
-- variations, olympic lifts, and previously missing muscle groups.
-- Enum values (Forearms, Traps, EZ Bar) added in 0044.
-- Existing exercise IDs are NOT modified.
-- =============================================================

-- ── Insert new exercises ─────────────────────────────────────
-- Uses ON CONFLICT to skip any that already exist (idempotent).

INSERT INTO exercises (id, name, muscle_group, equipment, category, default_sets, default_reps, rest_seconds, instructions, primary_regions, secondary_regions)
VALUES

-- ── CHEST (new) ──────────────────────────────────────────────
('ex_dcbp',
 'Decline Barbell Press',
 'Chest', 'Barbell', 'Strength',
 3, '8-10', 90,
 'Decline bench at 15-30°. Grip shoulder width, lower bar to lower chest.',
 ARRAY['mid_chest'],
 ARRAY['triceps', 'front_delts']),

('ex_ddbp',
 'Decline Dumbbell Press',
 'Chest', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Decline bench at 15-30°. Press dumbbells from lower chest, squeeze at top.',
 ARRAY['mid_chest'],
 ARRAY['triceps', 'front_delts']),

('ex_lcf',
 'Low-to-High Cable Fly',
 'Chest', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Cables set low. Fly upward in an arc, targeting upper chest.',
 ARRAY['upper_chest'],
 ARRAY['front_delts']),

('ex_hcf',
 'High-to-Low Cable Fly',
 'Chest', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Cables set high. Fly downward in an arc, targeting lower chest.',
 ARRAY['mid_chest'],
 ARRAY['front_delts']),

('ex_mcp',
 'Machine Chest Press',
 'Chest', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Seat adjusted so handles are at mid-chest. Press forward, control return.',
 ARRAY['mid_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_pdk',
 'Pec Deck',
 'Chest', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Elbows on pads at shoulder height. Squeeze handles together, slow return.',
 ARRAY['mid_chest'],
 ARRAY['front_delts']),

('ex_smbp',
 'Smith Machine Bench Press',
 'Chest', 'Smith Machine', 'Hypertrophy',
 3, '8-12', 90,
 'Lie flat under Smith bar. Lower to mid-chest, press up along fixed path.',
 ARRAY['mid_chest', 'front_delts'],
 ARRAY['triceps']),

('ex_pup',
 'Push-Up',
 'Chest', 'Bodyweight', 'Endurance',
 3, '15-25', 60,
 'Hands shoulder-width. Lower chest to ground, push up. Keep core tight.',
 ARRAY['mid_chest', 'triceps'],
 ARRAY['front_delts', 'abs']),

('ex_svp',
 'Svend Press',
 'Chest', 'Bodyweight', 'Hypertrophy',
 3, '12-15', 60,
 'Squeeze two plates together at chest. Press forward while maintaining squeeze.',
 ARRAY['mid_chest'],
 ARRAY['front_delts']),

-- ── BACK (new) ───────────────────────────────────────────────
('ex_sdl',
 'Sumo Deadlift',
 'Back', 'Barbell', 'Strength',
 4, '3-5', 180,
 'Wide stance, toes out. Grip inside knees. Drive hips forward to lockout.',
 ARRAY['glutes', 'quads', 'lower_back'],
 ARRAY['hamstrings', 'adductors', 'upper_back']),

('ex_tbdl',
 'Trap Bar Deadlift',
 'Back', 'Barbell', 'Strength',
 4, '5-8', 180,
 'Stand inside trap bar. Neutral grip handles. Push floor away, stand tall.',
 ARRAY['quads', 'glutes', 'lower_back'],
 ARRAY['hamstrings', 'upper_back', 'forearms']),

('ex_pdr',
 'Pendlay Row',
 'Back', 'Barbell', 'Strength',
 4, '5-8', 120,
 'Torso parallel to floor. Pull explosively from floor to chest each rep. Reset on floor.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps', 'lower_back']),

('ex_tbr',
 'T-Bar Row',
 'Back', 'Barbell', 'Strength',
 3, '8-10', 90,
 'Straddle bar. V-handle or grip plates. Row to chest, squeeze shoulder blades.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps']),

('ex_chu',
 'Chin-Up',
 'Back', 'Bodyweight', 'Strength',
 4, '6-12', 120,
 'Shoulder-width underhand grip. Pull chin above bar, full hang at bottom.',
 ARRAY['lats', 'biceps'],
 ARRAY['upper_back', 'forearms']),

('ex_cglp',
 'Close-Grip Lat Pulldown',
 'Back', 'Cable', 'Hypertrophy',
 3, '10-12', 90,
 'Narrow V-handle or underhand grip. Pull to chest, squeeze lats at bottom.',
 ARRAY['lats'],
 ARRAY['biceps', 'upper_back']),

('ex_sap',
 'Straight-Arm Pulldown',
 'Back', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Arms straight, slight bend at elbow. Pull bar from head height to thighs. Squeeze lats.',
 ARRAY['lats'],
 ARRAY['upper_back']),

('ex_csr',
 'Chest-Supported Row',
 'Back', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Chest on pad. Pull handles to sides, squeeze shoulder blades. No momentum.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps']),

('ex_rkp',
 'Rack Pull',
 'Back', 'Barbell', 'Strength',
 3, '3-5', 180,
 'Bar set at knee height in rack. Hinge and grip, lockout with heavy weight.',
 ARRAY['upper_back', 'lower_back'],
 ARRAY['glutes', 'forearms', 'traps']),

('ex_hyp',
 'Back Extension',
 'Back', 'Bodyweight', 'Hypertrophy',
 3, '12-15', 60,
 'Lock hips on pad. Lower torso, extend back up to parallel. Hold weight for added resistance.',
 ARRAY['lower_back', 'glutes'],
 ARRAY['hamstrings']),

('ex_mdwr',
 'Meadows Row',
 'Back', 'Barbell', 'Hypertrophy',
 3, '10-12 each', 90,
 'Landmine single-arm row. Staggered stance, pull to hip. Great lat stretch.',
 ARRAY['lats', 'upper_back'],
 ARRAY['rear_delts', 'biceps']),

('ex_smr',
 'Seated Machine Row',
 'Back', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Chest against pad. Pull handles back, squeeze shoulder blades together.',
 ARRAY['upper_back', 'lats'],
 ARRAY['rear_delts', 'biceps']),

-- ── SHOULDERS (new) ──────────────────────────────────────────
('ex_arnp',
 'Arnold Press',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Start with palms facing you. Rotate outward as you press overhead.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['triceps']),

('ex_mshp',
 'Machine Shoulder Press',
 'Shoulders', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Adjust seat so handles are at shoulder height. Press up, control descent.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['triceps']),

('ex_smop',
 'Smith Machine OHP',
 'Shoulders', 'Smith Machine', 'Strength',
 3, '6-8', 120,
 'Seat under Smith bar. Press along fixed path from clavicle to lockout.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['triceps', 'traps']),

('ex_clr',
 'Cable Lateral Raise',
 'Shoulders', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Low cable to side. Raise arm to shoulder height. Constant tension throughout.',
 ARRAY['side_delts'],
 ARRAY['traps']),

('ex_mlr',
 'Machine Lateral Raise',
 'Shoulders', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Arms on pads. Raise to shoulder height, pause at top, slow descent.',
 ARRAY['side_delts'],
 ARRAY['traps']),

('ex_mrdf',
 'Machine Rear Delt Fly',
 'Shoulders', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Face pad, grip handles. Open arms in reverse fly motion. Squeeze rear delts.',
 ARRAY['rear_delts'],
 ARRAY['traps', 'upper_back']),

('ex_cfr',
 'Cable Front Raise',
 'Shoulders', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Low cable, straight bar or single handle. Raise to eye level. Constant tension.',
 ARRAY['front_delts'],
 ARRAY['side_delts']),

('ex_lur',
 'Lu Raise',
 'Shoulders', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Front raise to shoulder height, then arc to lateral raise position. Lower. One fluid motion.',
 ARRAY['front_delts', 'side_delts'],
 ARRAY['traps']),

('ex_lmp',
 'Landmine Press',
 'Shoulders', 'Barbell', 'Strength',
 3, '8-10', 90,
 'Bar in landmine. Cup end with both hands at chest. Press at ~45° angle.',
 ARRAY['front_delts', 'upper_chest'],
 ARRAY['triceps']),

('ex_upr',
 'Upright Row',
 'Shoulders', 'Barbell', 'Hypertrophy',
 3, '10-12', 60,
 'Narrow grip. Pull bar to chin, elbows lead. Avoid if shoulder impingement.',
 ARRAY['side_delts', 'traps'],
 ARRAY['front_delts', 'biceps']),

-- ── BICEPS (new) ─────────────────────────────────────────────
('ex_ezc',
 'EZ-Bar Curl',
 'Biceps', 'EZ Bar', 'Hypertrophy',
 3, '8-12', 60,
 'Angled grip reduces wrist strain. Curl with full ROM. Control descent.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_idbc',
 'Incline Dumbbell Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Bench at 45°. Arms hang behind torso for extra stretch. Curl up, slow down.',
 ARRAY['biceps'],
 ARRAY['forearms']),

('ex_conc',
 'Concentration Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Seated, elbow braced on inner thigh. Curl up, squeeze at top, slow negative.',
 ARRAY['biceps'],
 ARRAY[]::TEXT[]),

('ex_spdc',
 'Spider Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Chest on incline bench. Arms hang straight down. Curl up, peak contraction at top.',
 ARRAY['biceps'],
 ARRAY[]::TEXT[]),

('ex_mbc',
 'Machine Bicep Curl',
 'Biceps', 'Machine', 'Hypertrophy',
 3, '10-12', 60,
 'Elbows on pad. Curl handles to shoulders. Squeeze at top, slow negative.',
 ARRAY['biceps'],
 ARRAY[]::TEXT[]),

('ex_bayc',
 'Bayesian Cable Curl',
 'Biceps', 'Cable', 'Hypertrophy',
 3, '10-12', 60,
 'Face away from low cable. Arm behind body for max stretch. Curl forward.',
 ARRAY['biceps'],
 ARRAY[]::TEXT[]),

('ex_cbhc',
 'Cross-Body Hammer Curl',
 'Biceps', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 60,
 'Neutral grip. Curl across body toward opposite shoulder. Alternate arms.',
 ARRAY['biceps'],
 ARRAY['forearms']),

-- ── TRICEPS (new) ────────────────────────────────────────────
('ex_coe',
 'Cable Overhead Extension',
 'Triceps', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Face away from cable. Rope behind head. Extend overhead, squeeze at top.',
 ARRAY['triceps'],
 ARRAY[]::TEXT[]),

('ex_tkb',
 'Tricep Kickback',
 'Triceps', 'Dumbbell', 'Hypertrophy',
 3, '12-15', 60,
 'Hinge at hip, elbow pinned to side. Extend arm back fully. Squeeze at top.',
 ARRAY['triceps'],
 ARRAY[]::TEXT[]),

('ex_dmpu',
 'Diamond Push-Up',
 'Triceps', 'Bodyweight', 'Strength',
 3, '10-15', 60,
 'Hands together forming diamond. Lower chest to hands. Full extension.',
 ARRAY['triceps'],
 ARRAY['mid_chest', 'front_delts']),

('ex_tdm',
 'Tricep Dip Machine',
 'Triceps', 'Machine', 'Hypertrophy',
 3, '10-12', 60,
 'Upright torso to bias triceps. Press down, full extension, slow return.',
 ARRAY['triceps'],
 ARRAY['front_delts']),

('ex_bdip',
 'Bench Dip',
 'Triceps', 'Bodyweight', 'Hypertrophy',
 3, '12-15', 60,
 'Hands on bench behind you, feet forward. Lower body by bending elbows, push up.',
 ARRAY['triceps'],
 ARRAY['front_delts', 'mid_chest']),

('ex_jmp',
 'JM Press',
 'Triceps', 'Barbell', 'Strength',
 3, '6-8', 90,
 'Hybrid skull crusher and close-grip bench. Lower bar to chin level, press back up.',
 ARRAY['triceps'],
 ARRAY['mid_chest', 'front_delts']),

-- ── LEGS (new) ───────────────────────────────────────────────
('ex_gsq',
 'Goblet Squat',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Hold dumbbell at chest. Squat deep, elbows inside knees. Stay upright.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors']),

('ex_smsq',
 'Smith Machine Squat',
 'Legs', 'Smith Machine', 'Hypertrophy',
 3, '8-12', 90,
 'Feet slightly forward. Squat along guided path. Good for quad isolation.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors']),

('ex_hsq',
 'Hack Squat',
 'Legs', 'Machine', 'Hypertrophy',
 4, '8-12', 90,
 'Shoulders under pads, feet shoulder-width on platform. Squat deep, press up.',
 ARRAY['quads'],
 ARRAY['glutes', 'adductors']),

('ex_psq',
 'Pendulum Squat',
 'Legs', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Shoulders on pad. Hips travel on arc. Deep stretch on quads. Controlled reps.',
 ARRAY['quads'],
 ARRAY['glutes']),

('ex_slc',
 'Seated Leg Curl',
 'Legs', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Adjust pad above ankles. Curl heels toward glutes. Squeeze hamstrings.',
 ARRAY['hamstrings'],
 ARRAY['glutes']),

('ex_rlng',
 'Reverse Lunge',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '10-12 each', 60,
 'Step backward, lower back knee to floor. Front shin stays vertical.',
 ARRAY['quads', 'glutes'],
 ARRAY['hamstrings']),

('ex_stup',
 'Step-Up',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '10-12 each', 60,
 'Step onto box/bench at knee height. Drive through heel. Alternate legs.',
 ARRAY['quads', 'glutes'],
 ARRAY['hamstrings']),

('ex_hadd',
 'Hip Adductor Machine',
 'Legs', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Squeeze legs together against pads. Slow negative, pause at close.',
 ARRAY['adductors'],
 ARRAY[]::TEXT[]),

('ex_habd',
 'Hip Abductor Machine',
 'Legs', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Push legs apart against pads. Hold at open position, slow return.',
 ARRAY['glutes'],
 ARRAY[]::TEXT[]),

('ex_dbrdl',
 'Dumbbell Romanian Deadlift',
 'Legs', 'Dumbbell', 'Hypertrophy',
 3, '10-12', 90,
 'Hold dumbbells at sides. Hinge at hips, slide weights down legs. Feel stretch.',
 ARRAY['hamstrings', 'glutes'],
 ARRAY['lower_back']),

('ex_gm',
 'Good Morning',
 'Legs', 'Barbell', 'Strength',
 3, '8-10', 90,
 'Bar on back like squat. Hinge at hips, slight knee bend. Feel hamstring stretch.',
 ARRAY['hamstrings', 'lower_back'],
 ARRAY['glutes']),

('ex_sisq',
 'Sissy Squat',
 'Legs', 'Bodyweight', 'Hypertrophy',
 3, '10-15', 60,
 'Hold support. Lean back, bend knees forward, lower body. Intense quad stretch.',
 ARRAY['quads'],
 ARRAY[]::TEXT[]),

('ex_btsq',
 'Belt Squat',
 'Legs', 'Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Weight hangs from belt at hips. Squat deep. No spinal loading.',
 ARRAY['quads', 'glutes'],
 ARRAY['adductors']),

('ex_nhc',
 'Nordic Hamstring Curl',
 'Legs', 'Bodyweight', 'Strength',
 3, '5-8', 90,
 'Kneel, feet anchored. Slowly lower body forward. Use hamstrings to control descent.',
 ARRAY['hamstrings'],
 ARRAY['glutes']),

('ex_sllp',
 'Single-Leg Leg Press',
 'Legs', 'Machine', 'Hypertrophy',
 3, '10-12 each', 90,
 'One foot on platform. Press up, control descent. Fixes imbalances.',
 ARRAY['quads', 'glutes'],
 ARRAY['hamstrings']),

('ex_wlst',
 'Wall Sit',
 'Legs', 'Bodyweight', 'Endurance',
 3, '45-60s', 60,
 'Back flat on wall, thighs parallel to floor. Hold position. Burn in quads.',
 ARRAY['quads'],
 ARRAY['glutes']),

-- ── GLUTES (new) ─────────────────────────────────────────────
('ex_smht',
 'Smith Machine Hip Thrust',
 'Glutes', 'Smith Machine', 'Hypertrophy',
 3, '10-12', 90,
 'Upper back on bench. Bar on hip crease. Drive up along guided path.',
 ARRAY['glutes'],
 ARRAY['hamstrings']),

('ex_cpt',
 'Cable Pull-Through',
 'Glutes', 'Cable', 'Hypertrophy',
 3, '12-15', 60,
 'Face away from low cable. Hinge at hips, pull through legs. Squeeze glutes at top.',
 ARRAY['glutes', 'hamstrings'],
 ARRAY['lower_back']),

('ex_gkb',
 'Glute Kickback Machine',
 'Glutes', 'Machine', 'Hypertrophy',
 3, '12-15 each', 60,
 'Standing on platform, kick leg back against pad. Squeeze glute at top.',
 ARRAY['glutes'],
 ARRAY['hamstrings']),

('ex_ghr',
 'Glute-Ham Raise',
 'Glutes', 'Machine', 'Strength',
 3, '8-12', 90,
 'Knees on pad, feet locked. Lower torso, pull back up using hamstrings and glutes.',
 ARRAY['hamstrings', 'glutes'],
 ARRAY['lower_back']),

('ex_ckb',
 'Cable Glute Kickback',
 'Glutes', 'Cable', 'Hypertrophy',
 3, '12-15 each', 60,
 'Ankle strap on low cable. Kick leg back, squeeze glute. Slow return.',
 ARRAY['glutes'],
 ARRAY['hamstrings']),

('ex_frgp',
 'Frog Pump',
 'Glutes', 'Bodyweight', 'Hypertrophy',
 3, '20-30', 45,
 'Lie on back, soles together, knees out. Drive hips up squeezing glutes.',
 ARRAY['glutes'],
 ARRAY[]::TEXT[]),

('ex_slht',
 'Single-Leg Hip Thrust',
 'Glutes', 'Bodyweight', 'Strength',
 3, '10-12 each', 60,
 'Upper back on bench, one foot planted. Drive hips up, squeeze glute at top.',
 ARRAY['glutes'],
 ARRAY['hamstrings']),

-- ── CORE (new) ───────────────────────────────────────────────
('ex_splk',
 'Side Plank',
 'Core', 'Bodyweight', 'Endurance',
 3, '30s each', 60,
 'Stack feet or stagger. Forearm on ground. Hips up, body straight. Hold.',
 ARRAY['obliques'],
 ARRAY['abs', 'glutes']),

('ex_mcr',
 'Machine Crunch',
 'Core', 'Machine', 'Hypertrophy',
 3, '12-15', 60,
 'Chest on pad or handles. Crunch forward against resistance. Slow return.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_rtwt',
 'Russian Twist',
 'Core', 'Bodyweight', 'Hypertrophy',
 3, '20 total', 60,
 'Seated, lean back 45°. Rotate torso side to side. Hold weight for added difficulty.',
 ARRAY['obliques'],
 ARRAY['abs']),

('ex_bcr',
 'Bicycle Crunch',
 'Core', 'Bodyweight', 'Endurance',
 3, '20 total', 60,
 'Lie on back, hands behind head. Elbow to opposite knee in cycling motion.',
 ARRAY['abs', 'obliques'],
 ARRAY[]::TEXT[]),

('ex_dbug',
 'Dead Bug',
 'Core', 'Bodyweight', 'Endurance',
 3, '10 each', 60,
 'Lie on back, arms up, knees at 90°. Extend opposite arm and leg. Keep back flat.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_wdch',
 'Cable Woodchop',
 'Core', 'Cable', 'Hypertrophy',
 3, '12 each', 60,
 'Cable set high. Pull diagonally across body. Rotate torso, pivot back foot.',
 ARRAY['obliques'],
 ARRAY['abs']),

('ex_palp',
 'Pallof Press',
 'Core', 'Cable', 'Strength',
 3, '10-12 each', 60,
 'Stand sideways to cable. Press handle straight out. Resist rotation. Hold.',
 ARRAY['obliques', 'abs'],
 ARRAY[]::TEXT[]),

('ex_dsu',
 'Decline Sit-Up',
 'Core', 'Bodyweight', 'Hypertrophy',
 3, '15-20', 60,
 'Feet locked on decline bench. Sit up, touch elbows to thighs. Hold weight for extra.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_vup',
 'V-Up',
 'Core', 'Bodyweight', 'Strength',
 3, '12-15', 60,
 'Lie flat. Simultaneously raise legs and torso, touch toes at top. Control down.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_dgfl',
 'Dragon Flag',
 'Core', 'Bodyweight', 'Strength',
 3, '5-8', 60,
 'Lie on bench, grip behind head. Raise body as one rigid unit. Slow negative.',
 ARRAY['abs'],
 ARRAY['obliques', 'lower_back']),

('ex_scc',
 'Suitcase Carry',
 'Core', 'Dumbbell', 'Strength',
 3, '40m each', 60,
 'Heavy dumbbell in one hand. Walk upright, resist leaning. Anti-lateral flexion.',
 ARRAY['obliques', 'abs'],
 ARRAY['forearms', 'traps']),

('ex_hbh',
 'Hollow Body Hold',
 'Core', 'Bodyweight', 'Endurance',
 3, '30-45s', 60,
 'Lie on back, press lower back to floor. Arms overhead, legs straight, hold.',
 ARRAY['abs'],
 ARRAY['obliques']),

('ex_cpplk',
 'Copenhagen Plank',
 'Core', 'Bodyweight', 'Strength',
 3, '20-30s each', 60,
 'Side plank with top leg on bench. Bottom leg hangs. Hold. Works core + adductors.',
 ARRAY['obliques', 'adductors'],
 ARRAY['abs', 'glutes']),

-- ── CALVES (new) ─────────────────────────────────────────────
('ex_lpcr',
 'Leg Press Calf Raise',
 'Calves', 'Machine', 'Hypertrophy',
 3, '15-20', 45,
 'Toes on edge of leg press platform. Push with balls of feet. Full stretch and squeeze.',
 ARRAY['calves'],
 ARRAY[]::TEXT[]),

('ex_dkcr',
 'Donkey Calf Raise',
 'Calves', 'Machine', 'Hypertrophy',
 3, '15-20', 45,
 'Bent at hips, pad on lower back. Rise on toes, full stretch at bottom.',
 ARRAY['calves'],
 ARRAY[]::TEXT[]),

('ex_slcr',
 'Single-Leg Calf Raise',
 'Calves', 'Bodyweight', 'Hypertrophy',
 3, '15-20 each', 45,
 'Stand on edge of step on one foot. Full ROM calf raise. Hold dumbbell for weight.',
 ARRAY['calves'],
 ARRAY[]::TEXT[]),

-- ── FOREARMS (new muscle group) ──────────────────────────────
('ex_wrc',
 'Wrist Curl',
 'Forearms', 'Barbell', 'Hypertrophy',
 3, '15-20', 45,
 'Forearms on bench, palms up. Curl wrists up. Full ROM.',
 ARRAY['forearms'],
 ARRAY[]::TEXT[]),

('ex_rwc',
 'Reverse Wrist Curl',
 'Forearms', 'Barbell', 'Hypertrophy',
 3, '15-20', 45,
 'Forearms on bench, palms down. Extend wrists up. Light weight, high reps.',
 ARRAY['forearms'],
 ARRAY[]::TEXT[]),

('ex_rvc',
 'Reverse Curl',
 'Forearms', 'Barbell', 'Hypertrophy',
 3, '10-12', 60,
 'Overhand grip on barbell. Curl up keeping wrists straight. Targets brachioradialis.',
 ARRAY['forearms', 'biceps'],
 ARRAY[]::TEXT[]),

('ex_fwk',
 'Farmer''s Walk',
 'Forearms', 'Dumbbell', 'Strength',
 3, '40m', 90,
 'Heavy dumbbells at sides. Walk with upright posture, tight grip. Go for distance or time.',
 ARRAY['forearms', 'traps'],
 ARRAY['abs', 'glutes']),

-- ── TRAPS (new muscle group) ─────────────────────────────────
('ex_bbs',
 'Barbell Shrug',
 'Traps', 'Barbell', 'Hypertrophy',
 4, '10-15', 60,
 'Overhand grip, shoulder width. Shrug shoulders to ears. Hold at top, slow down.',
 ARRAY['traps'],
 ARRAY['forearms']),

('ex_dbs',
 'Dumbbell Shrug',
 'Traps', 'Dumbbell', 'Hypertrophy',
 4, '12-15', 60,
 'Dumbbells at sides. Shrug straight up, pause at top. No rolling.',
 ARRAY['traps'],
 ARRAY['forearms']),

('ex_sms',
 'Smith Machine Shrug',
 'Traps', 'Smith Machine', 'Hypertrophy',
 4, '12-15', 60,
 'Bar in front. Shrug along guided path. Heavy weight, controlled reps.',
 ARRAY['traps'],
 ARRAY['forearms']),

-- ── FULL BODY (new) ──────────────────────────────────────────
('ex_thrst',
 'Thruster',
 'Full Body', 'Barbell', 'Power',
 4, '8-10', 90,
 'Front squat into overhead press in one fluid motion. Drive from the legs.',
 ARRAY['quads', 'front_delts', 'glutes'],
 ARRAY['triceps', 'abs']),

('ex_clnp',
 'Clean and Press',
 'Full Body', 'Barbell', 'Power',
 4, '3-5', 120,
 'Power clean from floor to shoulders, then press overhead. Explosive hip drive.',
 ARRAY['quads', 'glutes', 'front_delts'],
 ARRAY['traps', 'upper_back', 'hamstrings']),

('ex_pcln',
 'Power Clean',
 'Full Body', 'Barbell', 'Power',
 4, '3-5', 120,
 'Explosive pull from floor, catch bar on front delts. Triple extension.',
 ARRAY['quads', 'glutes', 'hamstrings'],
 ARRAY['traps', 'upper_back', 'forearms']),

('ex_burp',
 'Burpee',
 'Full Body', 'Bodyweight', 'Endurance',
 3, '10-15', 60,
 'Squat, kick feet back to plank, push-up, jump feet forward, jump up.',
 ARRAY['quads', 'abs', 'mid_chest'],
 ARRAY['glutes', 'triceps', 'front_delts']),

('ex_tgu',
 'Turkish Get-Up',
 'Full Body', 'Kettlebell', 'Strength',
 3, '3-5 each', 90,
 'Lie down, press weight up. Stand up in stages while keeping arm locked overhead.',
 ARRAY['abs', 'front_delts', 'glutes'],
 ARRAY['obliques', 'quads', 'traps']),

('ex_dbth',
 'Dumbbell Thruster',
 'Full Body', 'Dumbbell', 'Power',
 3, '10-12', 90,
 'Dumbbells at shoulders. Squat, then drive up pressing overhead in one motion.',
 ARRAY['quads', 'front_delts', 'glutes'],
 ARRAY['triceps', 'abs']),

('ex_brsl',
 'Battle Rope Slam',
 'Full Body', 'Bodyweight', 'Power',
 3, '30s', 60,
 'Grip rope ends. Alternate or simultaneous slams. Drive from hips and shoulders.',
 ARRAY['front_delts', 'abs'],
 ARRAY['lats', 'glutes', 'forearms']),

('ex_sldp',
 'Sled Push',
 'Full Body', 'Machine', 'Power',
 3, '30m', 90,
 'Low handle position. Drive with legs, keep core tight. Sprint or steady pace.',
 ARRAY['quads', 'glutes'],
 ARRAY['hamstrings', 'abs', 'front_delts']),

('ex_sldl',
 'Sled Pull',
 'Full Body', 'Machine', 'Power',
 3, '30m', 90,
 'Face sled, pull toward you hand over hand, or walk backward with strap.',
 ARRAY['upper_back', 'lats', 'biceps'],
 ARRAY['glutes', 'hamstrings', 'forearms']),

('ex_mnmk',
 'Man Maker',
 'Full Body', 'Dumbbell', 'Power',
 3, '6-8', 120,
 'Push-up on dumbbells, row each side, jump to squat, thruster. One fluid sequence.',
 ARRAY['quads', 'front_delts', 'mid_chest'],
 ARRAY['lats', 'triceps', 'abs', 'glutes']),

('ex_row',
 'Rowing Machine',
 'Full Body', 'Machine', 'Endurance',
 1, '2000m', 120,
 'Drive with legs first, lean back, pull handle to chest. Reverse sequence on return.',
 ARRAY['quads', 'lats', 'upper_back'],
 ARRAY['hamstrings', 'biceps', 'abs']),

('ex_bxjp',
 'Box Jump',
 'Full Body', 'Bodyweight', 'Power',
 3, '8-10', 60,
 'Stand facing box. Squat and explode up, land softly with both feet. Step down.',
 ARRAY['quads', 'glutes'],
 ARRAY['hamstrings', 'calves'])

ON CONFLICT (id) DO NOTHING;
