-- 0105: Populate Spanish instructions for all 146 exercises

UPDATE exercises SET instructions_es = CASE id
  WHEN 'ex_bp' THEN 'Acuéstate, agarra la barra un poco más ancho que los hombros, baja al pecho medio, empuja hacia arriba.'
  WHEN 'ex_cfly' THEN 'Coloca los cables a la altura de los hombros. Junta las manijas con movimiento de abrazo.'
  WHEN 'ex_dcbp' THEN 'Banco declinado a 15-30°. Agarre al ancho de hombros, baja la barra al pecho bajo.'
  WHEN 'ex_ddbp' THEN 'Banco declinado a 15-30°. Empuja las mancuernas desde el pecho bajo, aprieta arriba.'
  WHEN 'ex_dbp' THEN 'Agarre neutro o pronado. Baja las mancuernas al nivel del pecho con codos a 75°.'
  WHEN 'ex_dfly' THEN 'Banco plano. Arco amplio, codos ligeramente flexionados. Aprieta el pecho arriba.'
  WHEN 'ex_hcf' THEN 'Cables en posición alta. Cruza hacia abajo en arco, enfocando pecho bajo.'
  WHEN 'ex_ibp' THEN 'Banco a 30-45°. Agarre un poco más cerrado. Baja la barra al pecho alto.'
  WHEN 'ex_idbp' THEN 'Inclinado a 30-45°. Mismo movimiento que press plano con mancuernas, enfocando pecho alto.'
  WHEN 'ex_lcf' THEN 'Cables en posición baja. Cruza hacia arriba en arco, enfocando pecho alto.'
  WHEN 'ex_mcp' THEN 'Ajusta el asiento para que las manijas queden al pecho medio. Empuja hacia adelante, controla el regreso.'
  WHEN 'ex_pdk' THEN 'Codos en las almohadillas a la altura de los hombros. Junta las manijas, regreso lento.'
  WHEN 'ex_pup' THEN 'Manos al ancho de hombros. Baja el pecho al suelo, empuja hacia arriba. Mantén el core firme.'
  WHEN 'ex_smbp' THEN 'Acuéstate bajo la barra Smith. Baja al pecho medio, empuja hacia arriba en la guía fija.'
  WHEN 'ex_svp' THEN 'Aprieta dos discos juntos al pecho. Empuja hacia adelante manteniendo la presión.'
  WHEN 'ex_dips' THEN 'Inclínate ligeramente hacia adelante para activar pecho. Rango completo, bloquea arriba.'
  WHEN 'ex_hyp' THEN 'Fija las caderas en la almohadilla. Baja el torso, extiende hasta quedar paralelo. Sostén peso para más resistencia.'
  WHEN 'ex_bbr' THEN 'Flexiona a ~45°. Jala la barra al pecho bajo o al ombligo. Codos pegados.'
  WHEN 'ex_cbr' THEN 'Siéntate erguido. Jala la manija al abdomen, aprieta las escápulas.'
  WHEN 'ex_csr' THEN 'Pecho contra la almohadilla. Jala las manijas a los lados, aprieta escápulas. Sin impulso.'
  WHEN 'ex_chu' THEN 'Agarre supino al ancho de hombros. Sube la barbilla por encima de la barra, extiende abajo del todo.'
  WHEN 'ex_cglp' THEN 'Manija V estrecha o agarre supino. Jala al pecho, aprieta los dorsales abajo.'
  WHEN 'ex_dl' THEN 'Pies al ancho de cadera. Flexiona, agarra fuera de las rodillas. Empuja caderas al frente hasta bloquear.'
  WHEN 'ex_dbr' THEN 'Rodilla y mano en el banco. Jala la mancuerna a la cadera, codo pegado al cuerpo.'
  WHEN 'ex_lp' THEN 'Agarre prono ancho. Jala la barra al pecho alto, codos hacia abajo.'
  WHEN 'ex_mdwr' THEN 'Remo a un brazo en landmine. Posición escalonada, jala a la cadera. Gran estiramiento de dorsal.'
  WHEN 'ex_pdr' THEN 'Torso paralelo al suelo. Jala explosivamente del suelo al pecho en cada rep. Apoya en el suelo.'
  WHEN 'ex_pu' THEN 'Agarre prono al ancho de hombros. Sube el pecho a la barra, extiende abajo del todo.'
  WHEN 'ex_rkp' THEN 'Barra a la altura de rodillas en el rack. Flexiona y agarra, bloquea con peso pesado.'
  WHEN 'ex_rdl' THEN 'Rodillas ligeramente flexionadas. Flexiona en las caderas, la barra baja por las piernas. Siente el estiramiento en isquios.'
  WHEN 'ex_smr' THEN 'Pecho contra la almohadilla. Jala las manijas hacia atrás, aprieta las escápulas.'
  WHEN 'ex_sap' THEN 'Brazos rectos, codos ligeramente flexionados. Jala la barra desde la cabeza hasta los muslos. Aprieta dorsales.'
  WHEN 'ex_sdl' THEN 'Postura amplia, puntas hacia afuera. Aåççgarre dentro de las rodillas. Empuja caderas al frente hasta bloquear.'
  WHEN 'ex_tbr' THEN 'A horcajadas sobre la barra. Manija V o agarra los discos. Rema al pecho, aprieta escápulas.'
  WHEN 'ex_tbdl' THEN 'De pie dentro de la barra trampa. Agarre neutro. Empuja el suelo, ponte de pie erguido.'
  WHEN 'ex_arnp' THEN 'Empieza con palmas hacia ti. Rota hacia afuera mientras empujas sobre la cabeza.'
  WHEN 'ex_cfr' THEN 'Cable bajo, barra recta o manija individual. Eleva a la altura de los ojos. Tensión constante.'
  WHEN 'ex_clr' THEN 'Cable bajo al costado. Eleva el brazo a la altura del hombro. Tensión constante.'
  WHEN 'ex_dbop' THEN 'Sentado o de pie. Empuja las mancuernas sobre la cabeza desde la altura de los hombros.'
  WHEN 'ex_fcu' THEN 'Cable a la altura de los ojos. Jala hacia la cara con codos abiertos, rota externamente.'
  WHEN 'ex_fr' THEN 'Alterna brazos. Eleva a la altura de los ojos con codos ligeramente flexionados.'
  WHEN 'ex_lmp' THEN 'Barra en landmine. Sujeta el extremo con ambas manos al pecho. Empuja a ~45°.'
  WHEN 'ex_lr' THEN 'Codos ligeramente flexionados. Eleva a la altura del hombro. Guía con los codos.'
  WHEN 'ex_lur' THEN 'Elevación frontal a la altura del hombro, luego arco a posición lateral. Baja. Un movimiento fluido.'
  WHEN 'ex_mlr' THEN 'Brazos en las almohadillas. Eleva a la altura del hombro, pausa arriba, baja lento.'
  WHEN 'ex_mrdf' THEN 'Cara contra la almohadilla, agarra las manijas. Abre los brazos en fly inverso. Aprieta deltoides posterior.'
  WHEN 'ex_mshp' THEN 'Ajusta el asiento para que las manijas queden a la altura de los hombros. Empuja arriba, controla la bajada.'
  WHEN 'ex_ohp' THEN 'Agarre al ancho de hombros. Barra desde la clavícula, empuja sobre la cabeza, bloquea arriba.'
  WHEN 'ex_rfly' THEN 'Flexiona a 45°. Eleva las mancuernas a los lados, guía con los codos.'
  WHEN 'ex_smop' THEN 'Sentado bajo la barra Smith. Empuja en la guía fija desde la clavícula hasta bloquear.'
  ELSE instructions_es
END
WHERE id IN ('ex_bp','ex_cfly','ex_dcbp','ex_ddbp','ex_dbp','ex_dfly','ex_hcf','ex_ibp','ex_idbp','ex_lcf','ex_mcp','ex_pdk','ex_pup','ex_smbp','ex_svp','ex_dips','ex_hyp','ex_bbr','ex_cbr','ex_csr','ex_chu','ex_cglp','ex_dl','ex_dbr','ex_lp','ex_mdwr','ex_pdr','ex_pu','ex_rkp','ex_rdl','ex_smr','ex_sap','ex_sdl','ex_tbr','ex_tbdl','ex_arnp','ex_cfr','ex_clr','ex_dbop','ex_fcu','ex_fr','ex_lmp','ex_lr','ex_lur','ex_mlr','ex_mrdf','ex_mshp','ex_ohp','ex_rfly','ex_smop');

UPDATE exercises
SET instructions_es = CASE id
  WHEN 'ex_upr' THEN 'Agarre estrecho. Sube la barra hasta el mentón, codos arriba. Evitar si hay pinzamiento de hombro.'
  WHEN 'ex_bbc' THEN 'Agarre supino a la anchura de hombros. Rango completo. Sin balanceo.'
  WHEN 'ex_bayc' THEN 'De espaldas a la polea baja. Brazo detrás del cuerpo para máximo estiramiento. Curl hacia adelante.'
  WHEN 'ex_cc' THEN 'Tensión constante. Usa barra recta o EZ.'
  WHEN 'ex_conc' THEN 'Sentado, codo apoyado en la cara interna del muslo. Sube, aprieta arriba, negativa lenta.'
  WHEN 'ex_cbhc' THEN 'Agarre neutro. Curl cruzando hacia el hombro opuesto. Alterna brazos.'
  WHEN 'ex_dbc' THEN 'Alternado o simultáneo. Supina en la parte alta. Rango completo.'
  WHEN 'ex_ezc' THEN 'El agarre angulado reduce tensión en muñecas. Rango completo. Controla la bajada.'
  WHEN 'ex_hc' THEN 'Agarre neutro en todo momento. Trabaja braquial y braquiorradial.'
  WHEN 'ex_idbc' THEN 'Banco a 45°. Brazos colgando detrás del torso para mayor estiramiento. Sube y baja lento.'
  WHEN 'ex_mbc' THEN 'Codos en el pad. Curl hasta los hombros. Aprieta arriba, negativa lenta.'
  WHEN 'ex_pcc' THEN 'Aísla el bíceps. Estiramiento completo abajo. Excéntrica lenta.'
  WHEN 'ex_spdc' THEN 'Pecho apoyado en banco inclinado. Brazos colgando. Curl arriba, contracción máxima en el tope.'
  WHEN 'ex_sq' THEN 'Barra alta o baja. Pies a la anchura de hombros. Baja hasta paralelo o más.'
  WHEN 'ex_bdip' THEN 'Manos en el banco detrás, pies adelante. Baja flexionando codos, empuja arriba.'
  WHEN 'ex_coe' THEN 'De espaldas a la polea. Cuerda detrás de la cabeza. Extiende arriba, aprieta al final.'
  WHEN 'ex_cgp' THEN 'Manos a 30-40 cm de separación. Codos pegados, baja hacia el pecho bajo.'
  WHEN 'ex_dmpu' THEN 'Manos juntas formando un diamante. Baja el pecho hasta las manos. Extensión completa.'
  WHEN 'ex_jmp' THEN 'Híbrido entre rompecráneos y press cerrado. Baja la barra a la altura del mentón, empuja arriba.'
  WHEN 'ex_oe' THEN 'Ambas manos en una mancuerna. Baja detrás de la cabeza, extiende completamente.'
  WHEN 'ex_ske' THEN 'Banco plano. Baja la barra hasta la frente, extiende hasta bloquear.'
  WHEN 'ex_tdm' THEN 'Torso erguido para enfocar tríceps. Empuja abajo, extensión completa, retorno lento.'
  WHEN 'ex_tkb' THEN 'Inclínate desde la cadera, codo pegado al costado. Extiende el brazo atrás. Aprieta arriba.'
  WHEN 'ex_tpd' THEN 'Cuerda o barra. Codos pegados a los costados. Extensión completa.'
  WHEN 'ex_btsq' THEN 'El peso cuelga del cinturón en la cadera. Sentadilla profunda. Sin carga en la columna.'
  WHEN 'ex_bdl' THEN 'Pie trasero elevado. Baja hasta que el muslo delantero esté paralelo. Controla la bajada.'
  WHEN 'ex_dbrdl' THEN 'Mancuernas a los lados. Bisagra de cadera, desliza el peso por las piernas. Siente el estiramiento.'
  WHEN 'ex_fsq' THEN 'Barra sobre deltoides frontales. Mantén el torso erguido. Rodillas siguen la línea de los pies.'
  WHEN 'ex_gsq' THEN 'Sostén la mancuerna al pecho. Sentadilla profunda, codos dentro de las rodillas. Torso recto.'
  WHEN 'ex_gm' THEN 'Barra en la espalda como sentadilla. Bisagra de cadera, ligera flexión de rodillas. Siente los isquios.'
  WHEN 'ex_hsq' THEN 'Hombros bajo los pads, pies a la anchura de hombros en la plataforma. Baja profundo, empuja arriba.'
  WHEN 'ex_habd' THEN 'Empuja las piernas hacia afuera contra los pads. Sostén abierto, retorno lento.'
  WHEN 'ex_hadd' THEN 'Junta las piernas contra los pads. Negativa lenta, pausa al cerrar.'
  WHEN 'ex_lc' THEN 'Tumbado o sentado. Rango completo. Aprieta isquios en la contracción máxima.'
  WHEN 'ex_le' THEN 'Aísla cuádriceps. Extensión completa, excéntrica lenta.'
  WHEN 'ex_lp_l' THEN 'Pies a la anchura de hombros. Baja hasta 90° en la rodilla. Extensión completa.'
  WHEN 'ex_nhc' THEN 'De rodillas, pies anclados. Baja el cuerpo lentamente hacia adelante. Controla con los isquios.'
  WHEN 'ex_psq' THEN 'Hombros en el pad. La cadera se mueve en arco. Estiramiento profundo de cuádriceps. Repeticiones controladas.'
  WHEN 'ex_rlng' THEN 'Da un paso atrás, baja la rodilla trasera al suelo. La tibia delantera se mantiene vertical.'
  WHEN 'ex_slc' THEN 'Ajusta el pad sobre los tobillos. Lleva los talones hacia los glúteos. Aprieta isquios.'
  WHEN 'ex_sllp' THEN 'Un pie en la plataforma. Empuja arriba, controla la bajada. Corrige desbalances.'
  WHEN 'ex_sisq' THEN 'Agárrate de un soporte. Inclínate atrás, rodillas adelante, baja el cuerpo. Estiramiento intenso de cuádriceps.'
  WHEN 'ex_smsq' THEN 'Pies ligeramente adelantados. Sentadilla en la guía. Bueno para aislar cuádriceps.'
  WHEN 'ex_stup' THEN 'Sube a un cajón a la altura de la rodilla. Empuja con el talón. Alterna piernas.'
  WHEN 'ex_lunge' THEN 'Da un paso adelante, baja la rodilla trasera casi al suelo. Torso erguido.'
  WHEN 'ex_wlst' THEN 'Espalda plana contra la pared, muslos paralelos al suelo. Mantén la posición. Quema en cuádriceps.'
  WHEN 'ex_ckb' THEN 'Tobillera en polea baja. Patada hacia atrás, aprieta el glúteo. Retorno lento.'
  WHEN 'ex_cpt' THEN 'De espaldas a la polea baja. Bisagra de cadera, tira entre las piernas. Aprieta glúteos arriba.'
  WHEN 'ex_frgp' THEN 'Tumbado boca arriba, plantas juntas, rodillas abiertas. Sube la cadera apretando glúteos.'
  WHEN 'ex_gkb' THEN 'De pie en la plataforma, patada hacia atrás contra el pad. Aprieta el glúteo arriba.'
END
WHERE id IN (
  'ex_upr','ex_bbc','ex_bayc','ex_cc','ex_conc','ex_cbhc','ex_dbc','ex_ezc',
  'ex_hc','ex_idbc','ex_mbc','ex_pcc','ex_spdc','ex_sq','ex_bdip','ex_coe',
  'ex_cgp','ex_dmpu','ex_jmp','ex_oe','ex_ske','ex_tdm','ex_tkb','ex_tpd',
  'ex_btsq','ex_bdl','ex_dbrdl','ex_fsq','ex_gsq','ex_gm','ex_hsq','ex_habd',
  'ex_hadd','ex_lc','ex_le','ex_lp_l','ex_nhc','ex_psq','ex_rlng','ex_slc',
  'ex_sllp','ex_sisq','ex_smsq','ex_stup','ex_lunge','ex_wlst','ex_ckb',
  'ex_cpt','ex_frgp','ex_gkb'
);

UPDATE exercises SET instructions_es = CASE id
  WHEN 'ex_ghr' THEN 'Rodillas en el pad, pies bloqueados. Baja el torso y sube usando isquios y glúteos.'
  WHEN 'ex_hth' THEN 'Espalda alta en el banco, barra en la cadera. Empuja caderas arriba, aprieta glúteos arriba.'
  WHEN 'ex_kg' THEN 'Bisagra de cadera, impulsa caderas hacia adelante de forma explosiva. La pesa sube a la altura del pecho.'
  WHEN 'ex_slht' THEN 'Espalda alta en el banco, un pie apoyado. Empuja caderas arriba, aprieta glúteo arriba.'
  WHEN 'ex_smht' THEN 'Espalda alta en el banco. Barra en el pliegue de la cadera. Empuja hacia arriba por la guía.'
  WHEN 'ex_abwh' THEN 'De rodillas, rueda hacia adelante con espalda recta. Tira de vuelta con los abdominales, no la cadera.'
  WHEN 'ex_bcr' THEN 'Acostado boca arriba, manos detrás de la cabeza. Codo al rodilla opuesta en movimiento de pedaleo.'
  WHEN 'ex_cr' THEN 'De rodillas, cuerda detrás de la cabeza. Encoge llevando codos hacia las rodillas.'
  WHEN 'ex_wdch' THEN 'Cable en posición alta. Tira en diagonal cruzando el cuerpo. Rota el torso, pivotea el pie trasero.'
  WHEN 'ex_cpplk' THEN 'Plancha lateral con pierna de arriba en el banco. Pierna de abajo colgando. Mantén. Trabaja core y aductores.'
  WHEN 'ex_dbug' THEN 'Acostado boca arriba, brazos arriba, rodillas a 90°. Extiende brazo y pierna opuestos. Espalda pegada al suelo.'
  WHEN 'ex_dsu' THEN 'Pies fijos en banco declinado. Sube tocando codos a muslos. Sostén peso para más intensidad.'
  WHEN 'ex_dgfl' THEN 'Acostado en banco, agarre detrás de la cabeza. Eleva el cuerpo rígido como una unidad. Negativa lenta.'
  WHEN 'ex_llr' THEN 'Colgado en barra, sube piernas a 90° o más. Controla el descenso.'
  WHEN 'ex_hbh' THEN 'Acostado boca arriba, lumbar pegada al suelo. Brazos extendidos, piernas rectas, mantén la posición.'
  WHEN 'ex_mcr' THEN 'Pecho contra el pad o agarres. Encoge hacia adelante contra la resistencia. Retorno lento.'
  WHEN 'ex_palp' THEN 'De lado al cable. Empuja el agarre recto hacia afuera. Resiste la rotación. Mantén.'
  WHEN 'ex_plank' THEN 'Antebrazos en el suelo. Cuerpo recto y rígido. Aprieta glúteos y abdominales.'
  WHEN 'ex_rtwt' THEN 'Sentado, inclínate 45° hacia atrás. Rota el torso de lado a lado. Sostén peso para más dificultad.'
  WHEN 'ex_splk' THEN 'Pies apilados o escalonados. Antebrazo en el suelo. Caderas arriba, cuerpo recto. Mantén.'
  WHEN 'ex_scc' THEN 'Mancuerna pesada en una mano. Camina erguido, resiste la inclinación lateral.'
  WHEN 'ex_vup' THEN 'Acostado boca arriba. Sube piernas y torso a la vez, toca los pies arriba. Baja con control.'
  WHEN 'ex_dkcr' THEN 'Flexionado en la cadera, pad en la espalda baja. Sube en puntas, estiramiento completo abajo.'
  WHEN 'ex_lpcr' THEN 'Puntas en el borde de la plataforma de prensa. Empuja con la bola del pie. Estiramiento y contracción completos.'
  WHEN 'ex_secr' THEN 'Trabaja el sóleo. Mismo énfasis en rango completo de movimiento.'
  WHEN 'ex_slcr' THEN 'De pie en el borde de un escalón con un pie. Elevación completa de gemelo. Sostén mancuerna para peso.'
  WHEN 'ex_scr' THEN 'Rango completo de movimiento. Pausa en el estiramiento abajo. Aprieta arriba.'
  WHEN 'ex_brsl' THEN 'Agarra los extremos de la cuerda. Golpes alternados o simultáneos. Impulsa desde caderas y hombros.'
  WHEN 'ex_bxjp' THEN 'De pie frente al cajón. Agáchate y salta explosivamente, aterriza suave con ambos pies. Baja caminando.'
  WHEN 'ex_burp' THEN 'Agáchate, lanza pies atrás a plancha, flexión, salta pies adelante, salta arriba.'
  WHEN 'ex_clnp' THEN 'Cargada desde el suelo a los hombros, luego press sobre la cabeza. Impulso explosivo de cadera.'
  WHEN 'ex_dbth' THEN 'Mancuernas en los hombros. Sentadilla, luego empuja arriba presionando sobre la cabeza en un solo movimiento.'
  WHEN 'ex_mnmk' THEN 'Flexión sobre mancuernas, remo a cada lado, salta a sentadilla, thruster. Una secuencia fluida.'
  WHEN 'ex_pcln' THEN 'Tirón explosivo desde el suelo, recibe la barra en deltoides frontales. Triple extensión.'
  WHEN 'ex_row' THEN 'Empuja primero con piernas, inclínate atrás, tira del agarre al pecho. Secuencia inversa al volver.'
  WHEN 'ex_sldl' THEN 'De frente al trineo, tira hacia ti mano sobre mano, o camina hacia atrás con la correa.'
  WHEN 'ex_sldp' THEN 'Agarre bajo. Empuja con las piernas, core firme. Sprint o ritmo constante.'
  WHEN 'ex_thrst' THEN 'Sentadilla frontal seguida de press sobre la cabeza en un movimiento fluido. Impulsa desde las piernas.'
  WHEN 'ex_tgu' THEN 'Acostado, presiona el peso arriba. Levántate por etapas manteniendo el brazo bloqueado sobre la cabeza.'
  WHEN 'ex_fwk' THEN 'Mancuernas pesadas a los lados. Camina con postura erguida y agarre firme. Ve por distancia o tiempo.'
  WHEN 'ex_rvc' THEN 'Agarre prono en la barra. Curl hacia arriba manteniendo muñecas rectas. Trabaja el braquiorradial.'
  WHEN 'ex_rwc' THEN 'Antebrazos en el banco, palmas abajo. Extiende muñecas hacia arriba. Peso ligero, muchas repeticiones.'
  WHEN 'ex_wrc' THEN 'Antebrazos en el banco, palmas arriba. Flexiona muñecas hacia arriba. Rango completo de movimiento.'
  WHEN 'ex_bbs' THEN 'Agarre prono, ancho de hombros. Encoge hombros hacia las orejas. Sostén arriba, baja lento.'
  WHEN 'ex_dbs' THEN 'Mancuernas a los lados. Encoge recto hacia arriba, pausa arriba. Sin rotar.'
  WHEN 'ex_sms' THEN 'Barra al frente. Encoge por la guía. Peso pesado, repeticiones controladas.'
  ELSE instructions_es
END
WHERE id IN ('ex_ghr','ex_hth','ex_kg','ex_slht','ex_smht','ex_abwh','ex_bcr','ex_cr','ex_wdch','ex_cpplk','ex_dbug','ex_dsu','ex_dgfl','ex_llr','ex_hbh','ex_mcr','ex_palp','ex_plank','ex_rtwt','ex_splk','ex_scc','ex_vup','ex_dkcr','ex_lpcr','ex_secr','ex_slcr','ex_scr','ex_brsl','ex_bxjp','ex_burp','ex_clnp','ex_dbth','ex_mnmk','ex_pcln','ex_row','ex_sldl','ex_sldp','ex_thrst','ex_tgu','ex_fwk','ex_rvc','ex_rwc','ex_wrc','ex_bbs','ex_dbs','ex_sms');
